#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

#region Import functions

# define the following classes in PowerShell
try {
    Add-Type -AssemblyName System.Web -ErrorAction Ignore | Out-Null
    Add-Type -AssemblyName System.Net -ErrorAction Ignore | Out-Null
} catch {
    Write-Verbose $_
}

#region classes
class PrismSession {
    [string]$BaseUrl
    [string]$Authorization
}

#endregion
# set $ErrorActionPreference to 'Stop' globally
$ErrorActionPreference = 'Stop'

# store the API client's configuration
$Script:Configuration = [System.Collections.HashTable]@{}

$Script:CmdletBindingParameters = @('Verbose','Debug','ErrorAction','WarningAction','InformationAction','ErrorVariable','WarningVariable','InformationVariable','OutVariable','OutBuffer','PipelineVariable')

'Client', 'Public', 'Private' | Where-Object {
    Join-Path $PSScriptRoot $_ | Test-Path
} | Get-ChildItem -Path {
    Join-Path $PSScriptRoot $_
} -Filter '*.ps1' | ForEach-Object {
    Write-Debug "Importing file: $($_.BaseName)"
    try {
        . $_.FullName
    } catch {
        Write-Error -Message "Failed to import function $($_.Fullname): $_"
    }
}

if (Test-Path "$PSScriptRoot\Submodules") {
    # sub-modules
    Get-ChildItem "$PSScriptRoot\Submodules\*\*\*.psm1" |
    ForEach-Object { Import-Module $_.FullName -Force -DisableNameChecking }
}
#endregion