#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ClustermgmtV41ConfigComponentType.

.DESCRIPTION

Type of component.
#>

enum ClustermgmtV41ConfigComponentType {
    # enum value: "EXTENT_GROUP_REPLICAS"
    EXTENT_GROUP_REPLICAS
    # enum value: "OPLOG_EPISODES"
    OPLOG_EPISODES
    # enum value: "CASSANDRA_RING"
    CASSANDRA_RING
    # enum value: "ZOOKEPER_INSTANCES"
    ZOOKEPER_INSTANCES
    # enum value: "FREE_SPACE"
    FREE_SPACE
    # enum value: "STATIC_CONFIG"
    STATIC_CONFIG
    # enum value: "ERASURE_CODE_STRIP_SIZE"
    ERASURE_CODE_STRIP_SIZE
    # enum value: "STARGATE_HEALTH"
    STARGATE_HEALTH
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

