#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Map providing additional node attributes for the unconfigured node.

.PARAMETER LcmFamily
LCM family name.
.PARAMETER IsModelSupported
Indicates whether the model is supported or not.
.PARAMETER DefaultWorkload
Default workload.
.PARAMETER ShouldWorkWith1GNic
Indicates if cvm interface can work with 1 GIG NIC or not.
.PARAMETER IsRoboMixedHypervisor
Indicates whether the hypervisor is robo mixed or not.
.OUTPUTS

ClustermgmtV41ConfigUnconfiguredNodeAttributeMap<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigUnconfiguredNodeAttributeMap {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LcmFamily},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsModelSupported},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DefaultWorkload},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ShouldWorkWith1GNic},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsRoboMixedHypervisor}
    )

    Process {
        'Creating PSCustomObject: clustermgmt => ClustermgmtV41ConfigUnconfiguredNodeAttributeMap' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "lcmFamily" = ${LcmFamily}
            "isModelSupported" = ${IsModelSupported}
            "defaultWorkload" = ${DefaultWorkload}
            "shouldWorkWith1GNic" = ${ShouldWorkWith1GNic}
            "isRoboMixedHypervisor" = ${IsRoboMixedHypervisor}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigUnconfiguredNodeAttributeMap<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigUnconfiguredNodeAttributeMap<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigUnconfiguredNodeAttributeMap<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigUnconfiguredNodeAttributeMap {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: clustermgmt => ClustermgmtV41ConfigUnconfiguredNodeAttributeMap' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigUnconfiguredNodeAttributeMap
        $AllProperties = ("lcmFamily", "isModelSupported", "defaultWorkload", "shouldWorkWith1GNic", "isRoboMixedHypervisor")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lcmFamily"))) { #optional property not found
            $LcmFamily = $null
        } else {
            $LcmFamily = $JsonParameters.PSobject.Properties["lcmFamily"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isModelSupported"))) { #optional property not found
            $IsModelSupported = $null
        } else {
            $IsModelSupported = $JsonParameters.PSobject.Properties["isModelSupported"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "defaultWorkload"))) { #optional property not found
            $DefaultWorkload = $null
        } else {
            $DefaultWorkload = $JsonParameters.PSobject.Properties["defaultWorkload"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shouldWorkWith1GNic"))) { #optional property not found
            $ShouldWorkWith1GNic = $null
        } else {
            $ShouldWorkWith1GNic = $JsonParameters.PSobject.Properties["shouldWorkWith1GNic"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isRoboMixedHypervisor"))) { #optional property not found
            $IsRoboMixedHypervisor = $null
        } else {
            $IsRoboMixedHypervisor = $JsonParameters.PSobject.Properties["isRoboMixedHypervisor"].value
        }

        $PSO = [PSCustomObject]@{
            "lcmFamily" = ${LcmFamily}
            "isModelSupported" = ${IsModelSupported}
            "defaultWorkload" = ${DefaultWorkload}
            "shouldWorkWith1GNic" = ${ShouldWorkWith1GNic}
            "isRoboMixedHypervisor" = ${IsRoboMixedHypervisor}
        }

        return $PSO
    }

}

