#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Physical GPU configuration details.

.PARAMETER Type
No description available.
.PARAMETER DeviceId
Device Id.
.PARAMETER DeviceName
Device name.
.PARAMETER VendorName
Vendor name.
.PARAMETER IsInUse
GPU in use.
.PARAMETER Sbdf
SBDF address.
.PARAMETER NumaNode
NUMA node.
.PARAMETER Assignable
GPU assignable.
.PARAMETER Mode
No description available.
.PARAMETER FrameBufferSizeBytes
Frame buffer size in bytes.
.OUTPUTS

ClustermgmtV41ConfigPhysicalGpuConfig<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigPhysicalGpuConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("PASSTHROUGH_GRAPHICS", "PASSTHROUGH_COMPUTE", "VIRTUAL", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${Type},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${DeviceId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DeviceName},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VendorName},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsInUse} = $false,
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Sbdf},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NumaNode},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${Assignable},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("UNUSED", "USED_FOR_PASSTHROUGH", "USED_FOR_VIRTUAL", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${Mode},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${FrameBufferSizeBytes}
    )

    Process {
        'Creating PSCustomObject: clustermgmt => ClustermgmtV41ConfigPhysicalGpuConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$DeviceName -and $DeviceName.length -gt 128) {
            throw "invalid value for 'DeviceName', the character length must be smaller than or equal to 128."
        }

        if (!$DeviceName -and $DeviceName.length -lt 0) {
            throw "invalid value for 'DeviceName', the character length must be greater than or equal to 0."
        }

        if (!$VendorName -and $VendorName.length -gt 128) {
            throw "invalid value for 'VendorName', the character length must be smaller than or equal to 128."
        }

        if (!$VendorName -and $VendorName.length -lt 0) {
            throw "invalid value for 'VendorName', the character length must be greater than or equal to 0."
        }

        if (!$Sbdf -and $Sbdf.length -gt 11) {
            throw "invalid value for 'Sbdf', the character length must be smaller than or equal to 11."
        }

        if (!$Sbdf -and $Sbdf.length -lt 0) {
            throw "invalid value for 'Sbdf', the character length must be greater than or equal to 0."
        }

        if (!$NumaNode -and $NumaNode.length -gt 2) {
            throw "invalid value for 'NumaNode', the character length must be smaller than or equal to 2."
        }

        if (!$NumaNode -and $NumaNode.length -lt 0) {
            throw "invalid value for 'NumaNode', the character length must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "type" = ${Type}
            "deviceId" = ${DeviceId}
            "deviceName" = ${DeviceName}
            "vendorName" = ${VendorName}
            "isInUse" = ${IsInUse}
            "sbdf" = ${Sbdf}
            "numaNode" = ${NumaNode}
            "assignable" = ${Assignable}
            "mode" = ${Mode}
            "frameBufferSizeBytes" = ${FrameBufferSizeBytes}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigPhysicalGpuConfig<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigPhysicalGpuConfig<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigPhysicalGpuConfig<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigPhysicalGpuConfig {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: clustermgmt => ClustermgmtV41ConfigPhysicalGpuConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigPhysicalGpuConfig
        $AllProperties = ("type", "deviceId", "deviceName", "vendorName", "isInUse", "sbdf", "numaNode", "assignable", "mode", "frameBufferSizeBytes")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "deviceId"))) { #optional property not found
            $DeviceId = $null
        } else {
            $DeviceId = $JsonParameters.PSobject.Properties["deviceId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "deviceName"))) { #optional property not found
            $DeviceName = $null
        } else {
            $DeviceName = $JsonParameters.PSobject.Properties["deviceName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vendorName"))) { #optional property not found
            $VendorName = $null
        } else {
            $VendorName = $JsonParameters.PSobject.Properties["vendorName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isInUse"))) { #optional property not found
            $IsInUse = $null
        } else {
            $IsInUse = $JsonParameters.PSobject.Properties["isInUse"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sbdf"))) { #optional property not found
            $Sbdf = $null
        } else {
            $Sbdf = $JsonParameters.PSobject.Properties["sbdf"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numaNode"))) { #optional property not found
            $NumaNode = $null
        } else {
            $NumaNode = $JsonParameters.PSobject.Properties["numaNode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "assignable"))) { #optional property not found
            $Assignable = $null
        } else {
            $Assignable = $JsonParameters.PSobject.Properties["assignable"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mode"))) { #optional property not found
            $Mode = $null
        } else {
            $Mode = $JsonParameters.PSobject.Properties["mode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "frameBufferSizeBytes"))) { #optional property not found
            $FrameBufferSizeBytes = $null
        } else {
            $FrameBufferSizeBytes = $JsonParameters.PSobject.Properties["frameBufferSizeBytes"].value
        }

        $PSO = [PSCustomObject]@{
            "type" = ${Type}
            "deviceId" = ${DeviceId}
            "deviceName" = ${DeviceName}
            "vendorName" = ${VendorName}
            "isInUse" = ${IsInUse}
            "sbdf" = ${Sbdf}
            "numaNode" = ${NumaNode}
            "assignable" = ${Assignable}
            "mode" = ${Mode}
            "frameBufferSizeBytes" = ${FrameBufferSizeBytes}
        }

        return $PSO
    }

}

