#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Mapping of key management device to certificate status list.

.PARAMETER KeyManagementServerName
Key management server name.
.PARAMETER IsCertificatePresent
Certificate status.
.OUTPUTS

ClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${KeyManagementServerName},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsCertificatePresent}
    )

    Process {
        'Creating PSCustomObject: clustermgmt => ClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$KeyManagementServerName -and $KeyManagementServerName.length -gt 64) {
            throw "invalid value for 'KeyManagementServerName', the character length must be smaller than or equal to 64."
        }


        $PSO = [PSCustomObject]@{
            "keyManagementServerName" = ${KeyManagementServerName}
            "isCertificatePresent" = ${IsCertificatePresent}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: clustermgmt => ClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigKeyManagementDeviceToCertStatusInfo
        $AllProperties = ("keyManagementServerName", "isCertificatePresent")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "keyManagementServerName"))) { #optional property not found
            $KeyManagementServerName = $null
        } else {
            $KeyManagementServerName = $JsonParameters.PSobject.Properties["keyManagementServerName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isCertificatePresent"))) { #optional property not found
            $IsCertificatePresent = $null
        } else {
            $IsCertificatePresent = $JsonParameters.PSobject.Properties["isCertificatePresent"].value
        }

        $PSO = [PSCustomObject]@{
            "keyManagementServerName" = ${KeyManagementServerName}
            "isCertificatePresent" = ${IsCertificatePresent}
        }

        return $PSO
    }

}

