#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ClustermgmtV41ErrorMessageSeverity.

.DESCRIPTION

Enum schema MessageSeverity
#>

enum ClustermgmtV41ErrorMessageSeverity {
    # enum value: "INFO"
    INFO
    # enum value: "WARNING"
    WARNING
    # enum value: "ERROR"
    ERROR
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

