#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Specifies the VmDisks of a VM for migration and the migration plan for them. If all the disks of a VM need to be migrated to the same storage container, only a single migration plan with only the external ID of the destination storage container is needed.  If the disks are being migrated to different containers, one plan per disk needs to be specified.

.PARAMETER MigrateDisks
No description available.
.OUTPUTS

VmmV41AhvConfigDiskMigrationParams<PSCustomObject>
#>

function Initialize-VmmV41AhvConfigDiskMigrationParams {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${MigrateDisks}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigDiskMigrationParams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "migrateDisks" = ${MigrateDisks}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigDiskMigrationParams<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigDiskMigrationParams<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigDiskMigrationParams<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvConfigDiskMigrationParams {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigDiskMigrationParams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvConfigDiskMigrationParams
        $AllProperties = ("migrateDisks")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "migrateDisks"))) { #optional property not found
            $MigrateDisks = $null
        } else {
            $MigrateDisks = $JsonParameters.PSobject.Properties["migrateDisks"].value
        }

        $PSO = [PSCustomObject]@{
            "migrateDisks" = ${MigrateDisks}
        }

        return $PSO
    }

}

