#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

List of categories to be disassociated from the VM.

.PARAMETER Categories
No description available.
.OUTPUTS

VmmV41AhvConfigDisassociateVmCategoriesParams<PSCustomObject>
#>

function Initialize-NtnxV4VmmV41AhvConfigDisassociateVmCategoriesParams {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Categories}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigDisassociateVmCategoriesParams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Categories -and $Categories.length -gt 256) {
            throw "invalid value for 'Categories', number of items must be less than or equal to 256."
        }

        if (!$Categories -and $Categories.length -lt 1) {
            throw "invalid value for 'Categories', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "categories" = ${Categories}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigDisassociateVmCategoriesParams<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigDisassociateVmCategoriesParams<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigDisassociateVmCategoriesParams<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToVmmV41AhvConfigDisassociateVmCategoriesParams {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigDisassociateVmCategoriesParams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvConfigDisassociateVmCategoriesParams
        $AllProperties = ("categories")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "categories"))) { #optional property not found
            $Categories = $null
        } else {
            $Categories = $JsonParameters.PSobject.Properties["categories"].value
        }

        $PSO = [PSCustomObject]@{
            "categories" = ${Categories}
        }

        return $PSO
    }

}

