#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

This schema is generated from SchemaValidationErrorMessage.java

.PARAMETER Location
The part of the request that failed validation. Validation can fail for path, query parameters, and request body.
.PARAMETER Message
The detailed message for the validation error.
.PARAMETER AttributePath
The path of the attribute that failed validation in the schema.
.OUTPUTS

VmmV41ErrorSchemaValidationErrorMessage<PSCustomObject>
#>

function Initialize-NtnxV4VmmV41ErrorSchemaValidationErrorMessage {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Location},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Message},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AttributePath}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41ErrorSchemaValidationErrorMessage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "location" = ${Location}
            "message" = ${Message}
            "attributePath" = ${AttributePath}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41ErrorSchemaValidationErrorMessage<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41ErrorSchemaValidationErrorMessage<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41ErrorSchemaValidationErrorMessage<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToVmmV41ErrorSchemaValidationErrorMessage {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41ErrorSchemaValidationErrorMessage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41ErrorSchemaValidationErrorMessage
        $AllProperties = ("location", "message", "attributePath")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "location"))) { #optional property not found
            $Location = $null
        } else {
            $Location = $JsonParameters.PSobject.Properties["location"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "message"))) { #optional property not found
            $Message = $null
        } else {
            $Message = $JsonParameters.PSobject.Properties["message"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "attributePath"))) { #optional property not found
            $AttributePath = $null
        } else {
            $AttributePath = $JsonParameters.PSobject.Properties["attributePath"].value
        }

        $PSO = [PSCustomObject]@{
            "location" = ${Location}
            "message" = ${Message}
            "attributePath" = ${AttributePath}
        }

        return $PSO
    }

}

