#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Storage provided by Nutanix ADSF.

.PARAMETER DiskSizeBytes
Size of the disk in bytes.
.PARAMETER StorageContainer
No description available.
.PARAMETER StorageConfig
No description available.
.OUTPUTS

VmmV41EsxiConfigVmDisk<PSCustomObject>
#>

function Initialize-NtnxV4VmmV41EsxiConfigVmDisk {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${DiskSizeBytes},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${StorageContainer},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${StorageConfig}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiConfigVmDisk' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($DiskSizeBytes -and $DiskSizeBytes -lt 1) {
          throw "invalid value for 'DiskSizeBytes', must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "diskSizeBytes" = ${DiskSizeBytes}
            "storageContainer" = ${StorageContainer}
            "storageConfig" = ${StorageConfig}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41EsxiConfigVmDisk<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41EsxiConfigVmDisk<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41EsxiConfigVmDisk<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToVmmV41EsxiConfigVmDisk {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiConfigVmDisk' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41EsxiConfigVmDisk
        $AllProperties = ("diskSizeBytes", "storageContainer", "storageConfig")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "diskSizeBytes"))) { #optional property not found
            $DiskSizeBytes = $null
        } else {
            $DiskSizeBytes = $JsonParameters.PSobject.Properties["diskSizeBytes"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "storageContainer"))) { #optional property not found
            $StorageContainer = $null
        } else {
            $StorageContainer = $JsonParameters.PSobject.Properties["storageContainer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "storageConfig"))) { #optional property not found
            $StorageConfig = $null
        } else {
            $StorageConfig = $JsonParameters.PSobject.Properties["storageConfig"].value
        }

        $PSO = [PSCustomObject]@{
            "diskSizeBytes" = ${DiskSizeBytes}
            "storageContainer" = ${StorageContainer}
            "storageConfig" = ${StorageConfig}
        }

        return $PSO
    }

}

