#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

This field contains a Sysprep unattend xml definition, as a string. The value must be base64 encoded.

.PARAMETER Value
Value of Sysprep unattend xml definition. The value must be base64 encoded.
.OUTPUTS

VmmV41AhvConfigUnattendxml<PSCustomObject>
#>

function Initialize-VmmV41AhvConfigUnattendxml {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Value}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigUnattendxml' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Value -and $Value.length -gt 32000) {
            throw "invalid value for 'Value', the character length must be smaller than or equal to 32000."
        }


        $PSO = [PSCustomObject]@{
            "value" = ${Value}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigUnattendxml<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigUnattendxml<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigUnattendxml<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvConfigUnattendxml {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigUnattendxml' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvConfigUnattendxml
        $AllProperties = ("value")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "value"))) { #optional property not found
            $Value = $null
        } else {
            $Value = $JsonParameters.PSobject.Properties["value"].value
        }

        $PSO = [PSCustomObject]@{
            "value" = ${Value}
        }

        return $PSO
    }

}

