#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Arguments for installing Nutanix Guest Tools.

.PARAMETER Capabilities
The list of the application names that are enabled on the guest VM.
.PARAMETER Credential
No description available.
.PARAMETER RebootPreference
No description available.
.OUTPUTS

VmmV41EsxiConfigNutanixGuestToolsInstallConfig<PSCustomObject>
#>

function Initialize-NtnxV4VmmV41EsxiConfigNutanixGuestToolsInstallConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Capabilities},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Credential},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${RebootPreference}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiConfigNutanixGuestToolsInstallConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Capabilities -and $Capabilities.length -gt 2) {
            throw "invalid value for 'Capabilities', number of items must be less than or equal to 2."
        }

        if (!$Capabilities -and $Capabilities.length -lt 0) {
            throw "invalid value for 'Capabilities', number of items must be greater than or equal to 0."
        }

        if ($null -eq $Credential) {
            throw "invalid value for 'Credential', 'Credential' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "capabilities" = ${Capabilities}
            "credential" = ${Credential}
            "rebootPreference" = ${RebootPreference}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41EsxiConfigNutanixGuestToolsInstallConfig<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41EsxiConfigNutanixGuestToolsInstallConfig<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41EsxiConfigNutanixGuestToolsInstallConfig<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToVmmV41EsxiConfigNutanixGuestToolsInstallConfig {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiConfigNutanixGuestToolsInstallConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41EsxiConfigNutanixGuestToolsInstallConfig
        $AllProperties = ("capabilities", "credential", "rebootPreference")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'credential' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "credential"))) {
            throw "Error! JSON cannot be serialized due to the required property 'credential' missing."
        } else {
            $Credential = $JsonParameters.PSobject.Properties["credential"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "capabilities"))) { #optional property not found
            $Capabilities = $null
        } else {
            $Capabilities = $JsonParameters.PSobject.Properties["capabilities"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rebootPreference"))) { #optional property not found
            $RebootPreference = $null
        } else {
            $RebootPreference = $JsonParameters.PSobject.Properties["rebootPreference"].value
        }

        $PSO = [PSCustomObject]@{
            "capabilities" = ${Capabilities}
            "credential" = ${Credential}
            "rebootPreference" = ${RebootPreference}
        }

        return $PSO
    }

}

