#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Reference to an ADSF Volume Group.

.PARAMETER VolumeGroupExtId
The globally unique identifier of an ADSF volume group. It should be of type UUID.
.OUTPUTS

VmmV41AhvConfigADSFVolumeGroupReference<PSCustomObject>
#>

function Initialize-VmmV41AhvConfigADSFVolumeGroupReference {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${VolumeGroupExtId}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigADSFVolumeGroupReference' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $VolumeGroupExtId) {
            throw "invalid value for 'VolumeGroupExtId', 'VolumeGroupExtId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "volumeGroupExtId" = ${VolumeGroupExtId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigADSFVolumeGroupReference<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigADSFVolumeGroupReference<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigADSFVolumeGroupReference<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvConfigADSFVolumeGroupReference {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigADSFVolumeGroupReference' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvConfigADSFVolumeGroupReference
        $AllProperties = ("volumeGroupExtId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'volumeGroupExtId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "volumeGroupExtId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'volumeGroupExtId' missing."
        } else {
            $VolumeGroupExtId = $JsonParameters.PSobject.Properties["volumeGroupExtId"].value
        }

        $PSO = [PSCustomObject]@{
            "volumeGroupExtId" = ${VolumeGroupExtId}
        }

        return $PSO
    }

}

