#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum VmmV41ErrorMessageSeverity.

.DESCRIPTION

Enum schema MessageSeverity
#>

enum VmmV41ErrorMessageSeverity {
    # enum value: "INFO"
    INFO
    # enum value: "WARNING"
    WARNING
    # enum value: "ERROR"
    ERROR
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

