#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A collection of VM disk stats.

.PARAMETER Timestamp
The timestamp of a specific VM stats response data point.
.PARAMETER ControllerNumIops
The VM disk controller number of I/O operations per second.
.PARAMETER ControllerTotalReadIoTimeMicros
The VM disk controller total read I/O time in microseconds.
.PARAMETER ControllerNumWriteIo
The VM disk controller number of write I/O.
.PARAMETER ControllerTotalIoTimeMicros
The VM disk controller total I/O time in microseconds.
.PARAMETER ControllerNumSeqIo
The VM disk controller number of sequential I/O.
.PARAMETER ControllerTotalIoSizeKb
The VM disk controller total I/O size in kilobytes.
.PARAMETER ControllerNumIo
The VM disk controller number of I/O.
.PARAMETER ControllerWriteIoPpm
The VM disk controller percentage of write I/O in parts per million.
.PARAMETER ControllerNumWriteIops
The VM disk controller number of write I/O operations per second.
.PARAMETER ControllerAvgWriteIoLatencyMicros
The VM disk controller average write I/O latency in microseconds.
.PARAMETER ControllerNumReadIops
The VM disk controller number of read I/O operations per second.
.PARAMETER ControllerTotalReadIoSizeKb
The VM disk controller total read I/O size in kilobytes.
.PARAMETER ControllerReadIoPpm
The VM disk controller percentage of read I/O in parts per million.
.PARAMETER ControllerAvgIoLatencyMicros
The VM disk controller average I/O latency in microseconds.
.PARAMETER ControllerNumReadIo
The VM disk controller number of read I/O.
.PARAMETER ControllerSeqIoPpm
The VM disk controller percentage of sequential I/O in parts per million.
.PARAMETER ControllerReadIoBandwidthKbps
The VM disk controller number of read I/O bandwidth in kilobytes per second.
.PARAMETER ControllerIoBandwidthKbps
The VM disk controller number of I/O bandwidth in kilobytes per second.
.PARAMETER ControllerWriteIoBandwidthKbps
The VM disk controller write I/O bandwidth in kilobytes per second.
.PARAMETER ControllerUserBytes
The VM disk controller user bytes.
.PARAMETER ControllerRandomIoPpm
The VM disk controller percentage of random I/O in parts per million.
.PARAMETER ControllerAvgReadIoSizeKb
The VM disk controller average read I/O size in kilobytes.
.PARAMETER ControllerAvgWriteIoSizeKb
The VM disk controller average write I/O size in kilobytes.
.PARAMETER ControllerAvgReadIoLatencyMicros
The VM disk controller average read I/O latency in microseconds.
.PARAMETER ControllerTimespanMicros
The VM disk controller timespan in microseconds.
.OUTPUTS

VmmV41EsxiStatsVmDiskStatsTuple<PSCustomObject>
#>

function Initialize-NtnxV4VmmV41EsxiStatsVmDiskStatsTuple {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerNumIops},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerTotalReadIoTimeMicros},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerNumWriteIo},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerTotalIoTimeMicros},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerNumSeqIo},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerTotalIoSizeKb},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerNumIo},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerWriteIoPpm},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerNumWriteIops},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerAvgWriteIoLatencyMicros},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerNumReadIops},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerTotalReadIoSizeKb},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerReadIoPpm},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerAvgIoLatencyMicros},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerNumReadIo},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerSeqIoPpm},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerReadIoBandwidthKbps},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerIoBandwidthKbps},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerWriteIoBandwidthKbps},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerUserBytes},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerRandomIoPpm},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerAvgReadIoSizeKb},
        [Parameter(Position = 23, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerAvgWriteIoSizeKb},
        [Parameter(Position = 24, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerAvgReadIoLatencyMicros},
        [Parameter(Position = 25, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${ControllerTimespanMicros}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiStatsVmDiskStatsTuple' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "timestamp" = ${Timestamp}
            "controllerNumIops" = ${ControllerNumIops}
            "controllerTotalReadIoTimeMicros" = ${ControllerTotalReadIoTimeMicros}
            "controllerNumWriteIo" = ${ControllerNumWriteIo}
            "controllerTotalIoTimeMicros" = ${ControllerTotalIoTimeMicros}
            "controllerNumSeqIo" = ${ControllerNumSeqIo}
            "controllerTotalIoSizeKb" = ${ControllerTotalIoSizeKb}
            "controllerNumIo" = ${ControllerNumIo}
            "controllerWriteIoPpm" = ${ControllerWriteIoPpm}
            "controllerNumWriteIops" = ${ControllerNumWriteIops}
            "controllerAvgWriteIoLatencyMicros" = ${ControllerAvgWriteIoLatencyMicros}
            "controllerNumReadIops" = ${ControllerNumReadIops}
            "controllerTotalReadIoSizeKb" = ${ControllerTotalReadIoSizeKb}
            "controllerReadIoPpm" = ${ControllerReadIoPpm}
            "controllerAvgIoLatencyMicros" = ${ControllerAvgIoLatencyMicros}
            "controllerNumReadIo" = ${ControllerNumReadIo}
            "controllerSeqIoPpm" = ${ControllerSeqIoPpm}
            "controllerReadIoBandwidthKbps" = ${ControllerReadIoBandwidthKbps}
            "controllerIoBandwidthKbps" = ${ControllerIoBandwidthKbps}
            "controllerWriteIoBandwidthKbps" = ${ControllerWriteIoBandwidthKbps}
            "controllerUserBytes" = ${ControllerUserBytes}
            "controllerRandomIoPpm" = ${ControllerRandomIoPpm}
            "controllerAvgReadIoSizeKb" = ${ControllerAvgReadIoSizeKb}
            "controllerAvgWriteIoSizeKb" = ${ControllerAvgWriteIoSizeKb}
            "controllerAvgReadIoLatencyMicros" = ${ControllerAvgReadIoLatencyMicros}
            "controllerTimespanMicros" = ${ControllerTimespanMicros}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41EsxiStatsVmDiskStatsTuple<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41EsxiStatsVmDiskStatsTuple<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41EsxiStatsVmDiskStatsTuple<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToVmmV41EsxiStatsVmDiskStatsTuple {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiStatsVmDiskStatsTuple' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41EsxiStatsVmDiskStatsTuple
        $AllProperties = ("timestamp", "controllerNumIops", "controllerTotalReadIoTimeMicros", "controllerNumWriteIo", "controllerTotalIoTimeMicros", "controllerNumSeqIo", "controllerTotalIoSizeKb", "controllerNumIo", "controllerWriteIoPpm", "controllerNumWriteIops", "controllerAvgWriteIoLatencyMicros", "controllerNumReadIops", "controllerTotalReadIoSizeKb", "controllerReadIoPpm", "controllerAvgIoLatencyMicros", "controllerNumReadIo", "controllerSeqIoPpm", "controllerReadIoBandwidthKbps", "controllerIoBandwidthKbps", "controllerWriteIoBandwidthKbps", "controllerUserBytes", "controllerRandomIoPpm", "controllerAvgReadIoSizeKb", "controllerAvgWriteIoSizeKb", "controllerAvgReadIoLatencyMicros", "controllerTimespanMicros")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerNumIops"))) { #optional property not found
            $ControllerNumIops = $null
        } else {
            $ControllerNumIops = $JsonParameters.PSobject.Properties["controllerNumIops"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerTotalReadIoTimeMicros"))) { #optional property not found
            $ControllerTotalReadIoTimeMicros = $null
        } else {
            $ControllerTotalReadIoTimeMicros = $JsonParameters.PSobject.Properties["controllerTotalReadIoTimeMicros"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerNumWriteIo"))) { #optional property not found
            $ControllerNumWriteIo = $null
        } else {
            $ControllerNumWriteIo = $JsonParameters.PSobject.Properties["controllerNumWriteIo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerTotalIoTimeMicros"))) { #optional property not found
            $ControllerTotalIoTimeMicros = $null
        } else {
            $ControllerTotalIoTimeMicros = $JsonParameters.PSobject.Properties["controllerTotalIoTimeMicros"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerNumSeqIo"))) { #optional property not found
            $ControllerNumSeqIo = $null
        } else {
            $ControllerNumSeqIo = $JsonParameters.PSobject.Properties["controllerNumSeqIo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerTotalIoSizeKb"))) { #optional property not found
            $ControllerTotalIoSizeKb = $null
        } else {
            $ControllerTotalIoSizeKb = $JsonParameters.PSobject.Properties["controllerTotalIoSizeKb"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerNumIo"))) { #optional property not found
            $ControllerNumIo = $null
        } else {
            $ControllerNumIo = $JsonParameters.PSobject.Properties["controllerNumIo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerWriteIoPpm"))) { #optional property not found
            $ControllerWriteIoPpm = $null
        } else {
            $ControllerWriteIoPpm = $JsonParameters.PSobject.Properties["controllerWriteIoPpm"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerNumWriteIops"))) { #optional property not found
            $ControllerNumWriteIops = $null
        } else {
            $ControllerNumWriteIops = $JsonParameters.PSobject.Properties["controllerNumWriteIops"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerAvgWriteIoLatencyMicros"))) { #optional property not found
            $ControllerAvgWriteIoLatencyMicros = $null
        } else {
            $ControllerAvgWriteIoLatencyMicros = $JsonParameters.PSobject.Properties["controllerAvgWriteIoLatencyMicros"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerNumReadIops"))) { #optional property not found
            $ControllerNumReadIops = $null
        } else {
            $ControllerNumReadIops = $JsonParameters.PSobject.Properties["controllerNumReadIops"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerTotalReadIoSizeKb"))) { #optional property not found
            $ControllerTotalReadIoSizeKb = $null
        } else {
            $ControllerTotalReadIoSizeKb = $JsonParameters.PSobject.Properties["controllerTotalReadIoSizeKb"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerReadIoPpm"))) { #optional property not found
            $ControllerReadIoPpm = $null
        } else {
            $ControllerReadIoPpm = $JsonParameters.PSobject.Properties["controllerReadIoPpm"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerAvgIoLatencyMicros"))) { #optional property not found
            $ControllerAvgIoLatencyMicros = $null
        } else {
            $ControllerAvgIoLatencyMicros = $JsonParameters.PSobject.Properties["controllerAvgIoLatencyMicros"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerNumReadIo"))) { #optional property not found
            $ControllerNumReadIo = $null
        } else {
            $ControllerNumReadIo = $JsonParameters.PSobject.Properties["controllerNumReadIo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerSeqIoPpm"))) { #optional property not found
            $ControllerSeqIoPpm = $null
        } else {
            $ControllerSeqIoPpm = $JsonParameters.PSobject.Properties["controllerSeqIoPpm"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerReadIoBandwidthKbps"))) { #optional property not found
            $ControllerReadIoBandwidthKbps = $null
        } else {
            $ControllerReadIoBandwidthKbps = $JsonParameters.PSobject.Properties["controllerReadIoBandwidthKbps"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerIoBandwidthKbps"))) { #optional property not found
            $ControllerIoBandwidthKbps = $null
        } else {
            $ControllerIoBandwidthKbps = $JsonParameters.PSobject.Properties["controllerIoBandwidthKbps"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerWriteIoBandwidthKbps"))) { #optional property not found
            $ControllerWriteIoBandwidthKbps = $null
        } else {
            $ControllerWriteIoBandwidthKbps = $JsonParameters.PSobject.Properties["controllerWriteIoBandwidthKbps"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerUserBytes"))) { #optional property not found
            $ControllerUserBytes = $null
        } else {
            $ControllerUserBytes = $JsonParameters.PSobject.Properties["controllerUserBytes"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerRandomIoPpm"))) { #optional property not found
            $ControllerRandomIoPpm = $null
        } else {
            $ControllerRandomIoPpm = $JsonParameters.PSobject.Properties["controllerRandomIoPpm"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerAvgReadIoSizeKb"))) { #optional property not found
            $ControllerAvgReadIoSizeKb = $null
        } else {
            $ControllerAvgReadIoSizeKb = $JsonParameters.PSobject.Properties["controllerAvgReadIoSizeKb"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerAvgWriteIoSizeKb"))) { #optional property not found
            $ControllerAvgWriteIoSizeKb = $null
        } else {
            $ControllerAvgWriteIoSizeKb = $JsonParameters.PSobject.Properties["controllerAvgWriteIoSizeKb"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerAvgReadIoLatencyMicros"))) { #optional property not found
            $ControllerAvgReadIoLatencyMicros = $null
        } else {
            $ControllerAvgReadIoLatencyMicros = $JsonParameters.PSobject.Properties["controllerAvgReadIoLatencyMicros"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "controllerTimespanMicros"))) { #optional property not found
            $ControllerTimespanMicros = $null
        } else {
            $ControllerTimespanMicros = $JsonParameters.PSobject.Properties["controllerTimespanMicros"].value
        }

        $PSO = [PSCustomObject]@{
            "timestamp" = ${Timestamp}
            "controllerNumIops" = ${ControllerNumIops}
            "controllerTotalReadIoTimeMicros" = ${ControllerTotalReadIoTimeMicros}
            "controllerNumWriteIo" = ${ControllerNumWriteIo}
            "controllerTotalIoTimeMicros" = ${ControllerTotalIoTimeMicros}
            "controllerNumSeqIo" = ${ControllerNumSeqIo}
            "controllerTotalIoSizeKb" = ${ControllerTotalIoSizeKb}
            "controllerNumIo" = ${ControllerNumIo}
            "controllerWriteIoPpm" = ${ControllerWriteIoPpm}
            "controllerNumWriteIops" = ${ControllerNumWriteIops}
            "controllerAvgWriteIoLatencyMicros" = ${ControllerAvgWriteIoLatencyMicros}
            "controllerNumReadIops" = ${ControllerNumReadIops}
            "controllerTotalReadIoSizeKb" = ${ControllerTotalReadIoSizeKb}
            "controllerReadIoPpm" = ${ControllerReadIoPpm}
            "controllerAvgIoLatencyMicros" = ${ControllerAvgIoLatencyMicros}
            "controllerNumReadIo" = ${ControllerNumReadIo}
            "controllerSeqIoPpm" = ${ControllerSeqIoPpm}
            "controllerReadIoBandwidthKbps" = ${ControllerReadIoBandwidthKbps}
            "controllerIoBandwidthKbps" = ${ControllerIoBandwidthKbps}
            "controllerWriteIoBandwidthKbps" = ${ControllerWriteIoBandwidthKbps}
            "controllerUserBytes" = ${ControllerUserBytes}
            "controllerRandomIoPpm" = ${ControllerRandomIoPpm}
            "controllerAvgReadIoSizeKb" = ${ControllerAvgReadIoSizeKb}
            "controllerAvgWriteIoSizeKb" = ${ControllerAvgWriteIoSizeKb}
            "controllerAvgReadIoLatencyMicros" = ${ControllerAvgReadIoLatencyMicros}
            "controllerTimespanMicros" = ${ControllerTimespanMicros}
        }

        return $PSO
    }

}

