#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Defines how all the disks of a VM are migrated to the same target storage container.

.PARAMETER StorageContainer
No description available.
.OUTPUTS

VmmV41AhvConfigAllDisksMigrationPlan<PSCustomObject>
#>

function Initialize-NtnxV4VmmV41AhvConfigAllDisksMigrationPlan {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${StorageContainer}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigAllDisksMigrationPlan' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "storageContainer" = ${StorageContainer}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigAllDisksMigrationPlan<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigAllDisksMigrationPlan<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigAllDisksMigrationPlan<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToVmmV41AhvConfigAllDisksMigrationPlan {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigAllDisksMigrationPlan' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvConfigAllDisksMigrationPlan
        $AllProperties = ("storageContainer")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "storageContainer"))) { #optional property not found
            $StorageContainer = $null
        } else {
            $StorageContainer = $JsonParameters.PSobject.Properties["storageContainer"].value
        }

        $PSO = [PSCustomObject]@{
            "storageContainer" = ${StorageContainer}
        }

        return $PSO
    }

}

