#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The details about Nutanix Guest Tools for a VM.

.PARAMETER Version
Version of Nutanix Guest Tools installed on the VM.
.PARAMETER IsInstalled
Indicates whether Nutanix Guest Tools is installed on the VM or not.
.PARAMETER IsEnabled
Indicates whether Nutanix Guest Tools is enabled or not.
.PARAMETER IsIsoInserted
Indicates whether Nutanix Guest Tools ISO is inserted or not.
.PARAMETER Capabilities
The list of the application names that are enabled on the guest VM.
.PARAMETER AvailableVersion
Version of Nutanix Guest Tools available on the cluster.
.PARAMETER GuestOsVersion
Version of the operating system on the VM.
.PARAMETER IsReachable
Indicates whether the communication from VM to CVM is active or not.
.PARAMETER IsVssSnapshotCapable
Indicates whether the VM is configured to take VSS snapshots through NGT or not.
.PARAMETER IsVmMobilityDriversInstalled
Indicates whether the VM mobility drivers are installed on the VM or not.
.OUTPUTS

VmmV41EsxiConfigNutanixGuestTools<PSCustomObject>
#>

function Initialize-NtnxV4VmmV41EsxiConfigNutanixGuestTools {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Version},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsInstalled},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsEnabled},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsIsoInserted},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Capabilities},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AvailableVersion},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GuestOsVersion},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsReachable},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsVssSnapshotCapable},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsVmMobilityDriversInstalled}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiConfigNutanixGuestTools' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Capabilities -and $Capabilities.length -gt 2) {
            throw "invalid value for 'Capabilities', number of items must be less than or equal to 2."
        }

        if (!$Capabilities -and $Capabilities.length -lt 0) {
            throw "invalid value for 'Capabilities', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "version" = ${Version}
            "isInstalled" = ${IsInstalled}
            "isEnabled" = ${IsEnabled}
            "isIsoInserted" = ${IsIsoInserted}
            "capabilities" = ${Capabilities}
            "availableVersion" = ${AvailableVersion}
            "guestOsVersion" = ${GuestOsVersion}
            "isReachable" = ${IsReachable}
            "isVssSnapshotCapable" = ${IsVssSnapshotCapable}
            "isVmMobilityDriversInstalled" = ${IsVmMobilityDriversInstalled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41EsxiConfigNutanixGuestTools<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41EsxiConfigNutanixGuestTools<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41EsxiConfigNutanixGuestTools<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToVmmV41EsxiConfigNutanixGuestTools {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiConfigNutanixGuestTools' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41EsxiConfigNutanixGuestTools
        $AllProperties = ("version", "isInstalled", "isEnabled", "isIsoInserted", "capabilities", "availableVersion", "guestOsVersion", "isReachable", "isVssSnapshotCapable", "isVmMobilityDriversInstalled")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "version"))) { #optional property not found
            $Version = $null
        } else {
            $Version = $JsonParameters.PSobject.Properties["version"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isInstalled"))) { #optional property not found
            $IsInstalled = $null
        } else {
            $IsInstalled = $JsonParameters.PSobject.Properties["isInstalled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isEnabled"))) { #optional property not found
            $IsEnabled = $null
        } else {
            $IsEnabled = $JsonParameters.PSobject.Properties["isEnabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isIsoInserted"))) { #optional property not found
            $IsIsoInserted = $null
        } else {
            $IsIsoInserted = $JsonParameters.PSobject.Properties["isIsoInserted"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "capabilities"))) { #optional property not found
            $Capabilities = $null
        } else {
            $Capabilities = $JsonParameters.PSobject.Properties["capabilities"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "availableVersion"))) { #optional property not found
            $AvailableVersion = $null
        } else {
            $AvailableVersion = $JsonParameters.PSobject.Properties["availableVersion"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "guestOsVersion"))) { #optional property not found
            $GuestOsVersion = $null
        } else {
            $GuestOsVersion = $JsonParameters.PSobject.Properties["guestOsVersion"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isReachable"))) { #optional property not found
            $IsReachable = $null
        } else {
            $IsReachable = $JsonParameters.PSobject.Properties["isReachable"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isVssSnapshotCapable"))) { #optional property not found
            $IsVssSnapshotCapable = $null
        } else {
            $IsVssSnapshotCapable = $JsonParameters.PSobject.Properties["isVssSnapshotCapable"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isVmMobilityDriversInstalled"))) { #optional property not found
            $IsVmMobilityDriversInstalled = $null
        } else {
            $IsVmMobilityDriversInstalled = $JsonParameters.PSobject.Properties["isVmMobilityDriversInstalled"].value
        }

        $PSO = [PSCustomObject]@{
            "version" = ${Version}
            "isInstalled" = ${IsInstalled}
            "isEnabled" = ${IsEnabled}
            "isIsoInserted" = ${IsIsoInserted}
            "capabilities" = ${Capabilities}
            "availableVersion" = ${AvailableVersion}
            "guestOsVersion" = ${GuestOsVersion}
            "isReachable" = ${IsReachable}
            "isVssSnapshotCapable" = ${IsVssSnapshotCapable}
            "isVmMobilityDriversInstalled" = ${IsVmMobilityDriversInstalled}
        }

        return $PSO
    }

}

