#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Reference to the PCIe device.

.PARAMETER DeviceExtId
Globally unique identifier denoting PCIe device label. It should be of type UUID.
.OUTPUTS

VmmV41AhvConfigPcieDeviceReference<PSCustomObject>
#>

function Initialize-NtnxV4VmmV41AhvConfigPcieDeviceReference {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${DeviceExtId}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigPcieDeviceReference' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "deviceExtId" = ${DeviceExtId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigPcieDeviceReference<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigPcieDeviceReference<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigPcieDeviceReference<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToVmmV41AhvConfigPcieDeviceReference {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigPcieDeviceReference' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvConfigPcieDeviceReference
        $AllProperties = ("deviceExtId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "deviceExtId"))) { #optional property not found
            $DeviceExtId = $null
        } else {
            $DeviceExtId = $JsonParameters.PSobject.Properties["deviceExtId"].value
        }

        $PSO = [PSCustomObject]@{
            "deviceExtId" = ${DeviceExtId}
        }

        return $PSO
    }

}

