#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The metadata associated with an API response. This value is always present and minimally contains the self-link for the API request that produced this response. It also contains pagination data for the paginated requests. 

.PARAMETER Flags
An array of flags that may indicate the status of the response. For example, a flag with the name 'isPaginated' and value 'false', indicates that the response is not paginated. 
.PARAMETER Links
An array of HATEOAS style links for the response that may also include pagination links for list operations. 
.PARAMETER TotalAvailableResults
The total number of entities that are available on the server for this type. 
.PARAMETER Messages
Information, Warning or Error messages that might provide additional contextual information related to the operation. 
.PARAMETER ExtraInfo
An array of entity-specific metadata 
.OUTPUTS

CommonV10ResponseApiResponseMetadata<PSCustomObject>
#>

function Initialize-CommonV10ResponseApiResponseMetadata {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Flags},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Links},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${TotalAvailableResults},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Messages},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ExtraInfo}
    )

    Process {
        'Creating PSCustomObject: vmm => CommonV10ResponseApiResponseMetadata' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Flags -and $Flags.length -gt 20) {
            throw "invalid value for 'Flags', number of items must be less than or equal to 20."
        }

        if (!$Flags -and $Flags.length -lt 0) {
            throw "invalid value for 'Flags', number of items must be greater than or equal to 0."
        }

        if (!$Links -and $Links.length -gt 20) {
            throw "invalid value for 'Links', number of items must be less than or equal to 20."
        }

        if (!$Links -and $Links.length -lt 0) {
            throw "invalid value for 'Links', number of items must be greater than or equal to 0."
        }

        if (!$Messages -and $Messages.length -gt 20) {
            throw "invalid value for 'Messages', number of items must be less than or equal to 20."
        }

        if (!$Messages -and $Messages.length -lt 0) {
            throw "invalid value for 'Messages', number of items must be greater than or equal to 0."
        }

        if (!$ExtraInfo -and $ExtraInfo.length -gt 20) {
            throw "invalid value for 'ExtraInfo', number of items must be less than or equal to 20."
        }

        if (!$ExtraInfo -and $ExtraInfo.length -lt 0) {
            throw "invalid value for 'ExtraInfo', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "flags" = ${Flags}
            "links" = ${Links}
            "totalAvailableResults" = ${TotalAvailableResults}
            "messages" = ${Messages}
            "extraInfo" = ${ExtraInfo}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CommonV10ResponseApiResponseMetadata<PSCustomObject>

.DESCRIPTION

Convert from JSON to CommonV10ResponseApiResponseMetadata<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CommonV10ResponseApiResponseMetadata<PSCustomObject>
#>
function ConvertFrom-JsonToCommonV10ResponseApiResponseMetadata {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: vmm => CommonV10ResponseApiResponseMetadata' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CommonV10ResponseApiResponseMetadata
        $AllProperties = ("flags", "links", "totalAvailableResults", "messages", "extraInfo")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "flags"))) { #optional property not found
            $Flags = $null
        } else {
            $Flags = $JsonParameters.PSobject.Properties["flags"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "links"))) { #optional property not found
            $Links = $null
        } else {
            $Links = $JsonParameters.PSobject.Properties["links"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "totalAvailableResults"))) { #optional property not found
            $TotalAvailableResults = $null
        } else {
            $TotalAvailableResults = $JsonParameters.PSobject.Properties["totalAvailableResults"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "messages"))) { #optional property not found
            $Messages = $null
        } else {
            $Messages = $JsonParameters.PSobject.Properties["messages"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extraInfo"))) { #optional property not found
            $ExtraInfo = $null
        } else {
            $ExtraInfo = $JsonParameters.PSobject.Properties["extraInfo"].value
        }

        $PSO = [PSCustomObject]@{
            "flags" = ${Flags}
            "links" = ${Links}
            "totalAvailableResults" = ${TotalAvailableResults}
            "messages" = ${Messages}
            "extraInfo" = ${ExtraInfo}
        }

        return $PSO
    }

}

