#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum CommonV10StatsDownSamplingOperator.

.DESCRIPTION

The operator to use while performing down-sampling on stats data. Allowed values are SUM, MIN, MAX, AVG, COUNT and LAST. 
#>

enum CommonV10StatsDownSamplingOperator {
    # enum value: "SUM"
    SUM
    # enum value: "MIN"
    MIN
    # enum value: "MAX"
    MAX
    # enum value: "AVG"
    AVG
    # enum value: "COUNT"
    COUNT
    # enum value: "LAST"
    LAST
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

