#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Network identifier for this adapter. Only valid if nic_type is NORMAL_NIC or DIRECT_NIC.

.PARAMETER ExtId
The globally unique identifier of a subnet of type UUID.
.OUTPUTS

VmmV41AhvConfigSubnetReference<PSCustomObject>
#>

function Initialize-VmmV41AhvConfigSubnetReference {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ExtId}
    )

    Process {
        'Creating PSCustomObject: vmm => VmmV41AhvConfigSubnetReference' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "extId" = ${ExtId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigSubnetReference<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigSubnetReference<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigSubnetReference<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvConfigSubnetReference {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: vmm => VmmV41AhvConfigSubnetReference' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VmmV41AhvConfigSubnetReference
        $AllProperties = ("extId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extId"))) { #optional property not found
            $ExtId = $null
        } else {
            $ExtId = $JsonParameters.PSobject.Properties["extId"].value
        }

        $PSO = [PSCustomObject]@{
            "extId" = ${ExtId}
        }

        return $PSO
    }

}

