#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum VmmV41ContentImageType.

.DESCRIPTION

The type of an image.
#>

enum VmmV41ContentImageType {
    # enum value: "DISK_IMAGE"
    DISK_IMAGE
    # enum value: "ISO_IMAGE"
    ISO_IMAGE
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

