#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Ownership information for the VM.

.PARAMETER Owner
No description available.
.OUTPUTS

VmmV41EsxiConfigOwnershipInfo<PSCustomObject>
#>

function Initialize-VmmV41EsxiConfigOwnershipInfo {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Owner}
    )

    Process {
        'Creating PSCustomObject: vmm => VmmV41EsxiConfigOwnershipInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Owner) {
            throw "invalid value for 'Owner', 'Owner' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "owner" = ${Owner}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41EsxiConfigOwnershipInfo<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41EsxiConfigOwnershipInfo<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41EsxiConfigOwnershipInfo<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41EsxiConfigOwnershipInfo {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: vmm => VmmV41EsxiConfigOwnershipInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VmmV41EsxiConfigOwnershipInfo
        $AllProperties = ("owner")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'owner' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "owner"))) {
            throw "Error! JSON cannot be serialized due to the required property 'owner' missing."
        } else {
            $Owner = $JsonParameters.PSobject.Properties["owner"].value
        }

        $PSO = [PSCustomObject]@{
            "owner" = ${Owner}
        }

        return $PSO
    }

}

