#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum VmmV41AhvConfigNgtCapability.

.DESCRIPTION

The capabilities of the Nutanix Guest Tools in the VM.
#>

enum VmmV41AhvConfigNgtCapability {
    # enum value: "SELF_SERVICE_RESTORE"
    SELF_SERVICE_RESTORE
    # enum value: "VSS_SNAPSHOT"
    VSS_SNAPSHOT
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

