#
# Nutanix Files APIs
# Manage virtual file servers, create and configure shares for client access, protect them using DR and sync policies, provision storage space and administer security controls.
# Version: 4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Download user mappings

.DESCRIPTION

No description available.

.PARAMETER FileServerExtId
The external identifier of the file server.

.PARAMETER ReturnType

Select the return type (optional): application/octet-stream, application/json

.PARAMETER NoHttpInfo

A switch that'll return just the Response, instead of a hash table with the Response, StatusCode and Headers. Don't enable this switch unless you're doing something advanced, as the prism central v4 api requires the EType to be the current and valid type in order to modify objects. The EType is returned in the Headers.

.OUTPUTS

System.IO.FileInfo
#>
function Invoke-DownloadUserMappings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${FileServerExtId},
        [String]
        [ValidateSet("application/octet-stream", "application/json")]
        $ReturnType,
        [Switch]
        $NoHttpInfo
    )

    Process {
        'Calling method: Invoke-DownloadUserMappings' | Write-Debug $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/octet-stream', 'application/json')

        if ($ReturnType) {
            # use the return type (MIME) provided by the user
            $LocalVarAccepts = @($ReturnType)
        }

        $LocalVarUri = '/files/v4.0/config/file-servers/{fileServerExtId}/user-mappings'
        if (!$FileServerExtId) {
            throw "Error! The required parameter `FileServerExtId` missing when calling downloadUserMappings."
        }
        $LocalVarUri = $LocalVarUri.replace('{fileServerExtId}', [System.Web.HTTPUtility]::UrlEncode($FileServerExtId))

        $LocalVarResult = Send-ApiRequest -Method 'GET' `
			-Uri $LocalVarUri `
			-Accepts $LocalVarAccepts `
			-ContentTypes $LocalVarContentTypes `
			-Body $LocalVarBodyParameter `
			-HeaderParameters $LocalVarHeaderParameters `
			-QueryParameters $LocalVarQueryParameters `
			-FormParameters $LocalVarFormParameters `
			-CookieParameters $LocalVarCookieParameters `
			-ReturnType "System.IO.FileInfo" `
			-IsBodyNullable $false

        if ($NoHttpInfo.IsPresent) {
            return $LocalVarResult["Response"]
        } else {
            return $LocalVarResult
        }
    }
}

<#
.SYNOPSIS

Upload user mappings

.DESCRIPTION

No description available.

.PARAMETER FileServerExtId
The external identifier of the file server.

.PARAMETER NTNXRequestId
A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 

.PARAMETER Body
No description available.

.PARAMETER NoHttpInfo

A switch that'll return just the Response, instead of a hash table with the Response, StatusCode and Headers. Don't enable this switch unless you're doing something advanced, as the prism central v4 api requires the EType to be the current and valid type in order to modify objects. The EType is returned in the Headers.

.OUTPUTS

UploadUserMappings200Response
#>
function Invoke-UploadUserMappings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${FileServerExtId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${NTNXRequestId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.IO.FileInfo]
        ${Body},
        [Switch]
        $NoHttpInfo
    )

    Process {
        'Calling method: Invoke-UploadUserMappings' | Write-Debug $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        # HTTP header 'Content-Type'
        $LocalVarContentTypes = @('application/octet-stream')

        $LocalVarUri = '/files/v4.0/config/file-servers/{fileServerExtId}/$actions/upload-user-mappings'
        if (!$FileServerExtId) {
            throw "Error! The required parameter `FileServerExtId` missing when calling uploadUserMappings."
        }
        $LocalVarUri = $LocalVarUri.replace('{fileServerExtId}', [System.Web.HTTPUtility]::UrlEncode($FileServerExtId))

        if (!$NTNXRequestId) {
            throw "Error! The required parameter `NTNXRequestId` missing when calling uploadUserMappings."
        }
        $LocalVarHeaderParameters['NTNX-Request-Id'] = $NTNXRequestId

        if (!$Body) {
            throw "Error! The required parameter `Body` missing when calling uploadUserMappings."
        }

        $LocalVarBodyParameter = $Body | ConvertTo-Json -Depth 100

        $LocalVarResult = Send-ApiRequest -Method 'POST' `
			-Uri $LocalVarUri `
			-Accepts $LocalVarAccepts `
			-ContentTypes $LocalVarContentTypes `
			-Body $LocalVarBodyParameter `
			-HeaderParameters $LocalVarHeaderParameters `
			-QueryParameters $LocalVarQueryParameters `
			-FormParameters $LocalVarFormParameters `
			-CookieParameters $LocalVarCookieParameters `
			-ReturnType "UploadUserMappings200Response" `
			-IsBodyNullable $false

        if ($NoHttpInfo.IsPresent) {
            return $LocalVarResult["Response"]
        } else {
            return $LocalVarResult
        }
    }
}

