#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A single step in the task.

.PARAMETER Name
Message describing the completed steps for the task.
.OUTPUTS

PrismV41ConfigTaskStep<PSCustomObject>
#>

function Initialize-PrismV41ConfigTaskStep {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name}
    )

    Process {
        'Creating PSCustomObject: prism => PrismV41ConfigTaskStep' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Name -and $Name.length -gt 512) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 512."
        }


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PrismV41ConfigTaskStep<PSCustomObject>

.DESCRIPTION

Convert from JSON to PrismV41ConfigTaskStep<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PrismV41ConfigTaskStep<PSCustomObject>
#>
function ConvertFrom-JsonToPrismV41ConfigTaskStep {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: prism => PrismV41ConfigTaskStep' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PrismV41ConfigTaskStep
        $AllProperties = ("name")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
        }

        return $PSO
    }

}

