#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Payload to configure connection endpoint. It contains the details of the remote cluster you are connecting to.

.PARAMETER RemoteCluster
No description available.
.OUTPUTS

PrismV41ManagementConnectionConfigurationSpec<PSCustomObject>
#>

function Initialize-PrismV41ManagementConnectionConfigurationSpec {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${RemoteCluster}
    )

    Process {
        'Creating PSCustomObject: prism => PrismV41ManagementConnectionConfigurationSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $RemoteCluster) {
            throw "invalid value for 'RemoteCluster', 'RemoteCluster' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "remoteCluster" = ${RemoteCluster}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PrismV41ManagementConnectionConfigurationSpec<PSCustomObject>

.DESCRIPTION

Convert from JSON to PrismV41ManagementConnectionConfigurationSpec<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PrismV41ManagementConnectionConfigurationSpec<PSCustomObject>
#>
function ConvertFrom-JsonToPrismV41ManagementConnectionConfigurationSpec {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: prism => PrismV41ManagementConnectionConfigurationSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PrismV41ManagementConnectionConfigurationSpec
        $AllProperties = ("remoteCluster")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'remoteCluster' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "remoteCluster"))) {
            throw "Error! JSON cannot be serialized due to the required property 'remoteCluster' missing."
        } else {
            $RemoteCluster = $JsonParameters.PSobject.Properties["remoteCluster"].value
        }

        $PSO = [PSCustomObject]@{
            "remoteCluster" = ${RemoteCluster}
        }

        return $PSO
    }

}

