#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum PrismV41ManagementEnablementState.

.DESCRIPTION

Represents the status of enablement.
#>

enum PrismV41ManagementEnablementState {
    # enum value: "DISABLED"
    DISABLED
    # enum value: "ENABLED"
    ENABLED
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

