#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum PrismV41ManagementProductName.

.DESCRIPTION

Name of a product that is an enum string.
#>

enum PrismV41ManagementProductName {
    # enum value: "FLOW_VIRTUAL_NETWORKING"
    FLOW_VIRTUAL_NETWORKING
    # enum value: "FLOW_NETWORK_SECURITY"
    FLOW_NETWORK_SECURITY
    # enum value: "NUTANIX_DISASTER_RECOVERY"
    NUTANIX_DISASTER_RECOVERY
    # enum value: "SELF_SERVICE"
    SELF_SERVICE
    # enum value: "NUTANIX_MARKETPLACE"
    NUTANIX_MARKETPLACE
    # enum value: "INTELLIGENT_OPERATIONS"
    INTELLIGENT_OPERATIONS
    # enum value: "NUTANIX_CLOUD_MANAGER"
    NUTANIX_CLOUD_MANAGER
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

