#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Json

JSON object

.OUTPUTS

PrismV41ManagementGetBackupTargetApiResponseData<PSCustomObject>
#>
function ConvertFrom-JsonToPrismV41ManagementGetBackupTargetApiResponseData {
    [CmdletBinding()]
    Param (
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        $match = 0
        $matchType = $null
        $matchInstance = $null

        # try to match PrismV41ErrorErrorResponse defined in the oneOf schemas
        try {
            $matchInstance = ConvertFrom-JsonToPrismV41ErrorErrorResponse $Json

            foreach($property in $matchInstance.PsObject.Properties) {
                if ($null -ne $property.Value) {
                    $matchType = "PrismV41ErrorErrorResponse"
                    $match++
                    break
                }
            }
        } catch {
            # fail to match the schema defined in oneOf, proceed to the next one
            Write-Debug "Failed to match 'PrismV41ErrorErrorResponse' defined in oneOf (PrismV41ManagementGetBackupTargetApiResponseData). Proceeding to the next one if any."
        }

        # try to match PrismV41ManagementBackupTarget defined in the oneOf schemas
        try {
            $matchInstance = ConvertFrom-JsonToPrismV41ManagementBackupTarget $Json

            foreach($property in $matchInstance.PsObject.Properties) {
                if ($null -ne $property.Value) {
                    $matchType = "PrismV41ManagementBackupTarget"
                    $match++
                    break
                }
            }
        } catch {
            # fail to match the schema defined in oneOf, proceed to the next one
            Write-Debug "Failed to match 'PrismV41ManagementBackupTarget' defined in oneOf (PrismV41ManagementGetBackupTargetApiResponseData). Proceeding to the next one if any."
        }

        if ($match -gt 1) {
            throw "Error! The JSON payload matches more than one type defined in oneOf schemas ([PrismV41ErrorErrorResponse, PrismV41ManagementBackupTarget]). JSON Payload: $($Json)"
        } elseif ($match -eq 1) {
            return [PSCustomObject]@{
                "ActualType" = ${matchType}
                "ActualInstance" = ${matchInstance}
                "OneOfSchemas" = @("PrismV41ErrorErrorResponse", "PrismV41ManagementBackupTarget")
            }
        } else {
            throw "Error! The JSON payload doesn't matches any type defined in oneOf schemas ([PrismV41ErrorErrorResponse, PrismV41ManagementBackupTarget]). JSON Payload: $($Json)"
        }
    }
}

