#
# Nutanix Security APIs
# Manage security features, such as encryption, certificates, or platform hardening.
# Version: 4.0.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Secret fields of a Key based Authencation credential.

.PARAMETER ApiKey
Intersight connection API key.
.PARAMETER SecretKey
Secret key of the Intersight connection.
.OUTPUTS

SecurityV40ConfigKeyBasedAuth<PSCustomObject>
#>

function Initialize-SecurityV40ConfigKeyBasedAuth {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ApiKey},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SecretKey}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.security => NtnxV4SecurityV40ConfigKeyBasedAuth' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ApiKey) {
            throw "invalid value for 'ApiKey', 'ApiKey' cannot be null."
        }

        if ($ApiKey.length -gt 1024) {
            throw "invalid value for 'ApiKey', the character length must be smaller than or equal to 1024."
        }

        if ($ApiKey.length -lt 1) {
            throw "invalid value for 'ApiKey', the character length must be greater than or equal to 1."
        }

        if ($null -eq $SecretKey) {
            throw "invalid value for 'SecretKey', 'SecretKey' cannot be null."
        }

        if ($SecretKey.length -gt 2048) {
            throw "invalid value for 'SecretKey', the character length must be smaller than or equal to 2048."
        }

        if ($SecretKey.length -lt 1) {
            throw "invalid value for 'SecretKey', the character length must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "apiKey" = ${ApiKey}
            "secretKey" = ${SecretKey}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SecurityV40ConfigKeyBasedAuth<PSCustomObject>

.DESCRIPTION

Convert from JSON to SecurityV40ConfigKeyBasedAuth<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SecurityV40ConfigKeyBasedAuth<PSCustomObject>
#>
function ConvertFrom-JsonToSecurityV40ConfigKeyBasedAuth {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.security => NtnxV4SecurityV40ConfigKeyBasedAuth' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4SecurityV40ConfigKeyBasedAuth
        $AllProperties = ("apiKey", "secretKey")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'apiKey' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "apiKey"))) {
            throw "Error! JSON cannot be serialized due to the required property 'apiKey' missing."
        } else {
            $ApiKey = $JsonParameters.PSobject.Properties["apiKey"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "secretKey"))) {
            throw "Error! JSON cannot be serialized due to the required property 'secretKey' missing."
        } else {
            $SecretKey = $JsonParameters.PSobject.Properties["secretKey"].value
        }

        $PSO = [PSCustomObject]@{
            "apiKey" = ${ApiKey}
            "secretKey" = ${SecretKey}
        }

        return $PSO
    }

}

