#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

VM-Host Affinity policy configuration.

.PARAMETER TenantId
A globally unique identifier that represents the tenant that owns this entity. The system automatically assigns it, and it and is immutable from an API consumer perspective (some use cases may cause this ID to change - For instance, a use case may require the transfer of ownership of the entity, but these cases are handled automatically on the server). 
.PARAMETER ExtId
A globally unique identifier of an instance that is suitable for external consumption. 
.PARAMETER Links
A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource. 
.PARAMETER Name
VM-Host Affinity policy name.
.PARAMETER Description
VM-Host Affinity policy description.
.PARAMETER CreateTime
VM-Host Affinity policy creation time.
.PARAMETER UpdateTime
VM-Host Affinity policy last updated time.
.PARAMETER CreatedBy
No description available.
.PARAMETER LastUpdatedBy
No description available.
.PARAMETER VmCategories
Categories through which VM is associated with the VM-host affinity policy.
.PARAMETER HostCategories
Categories through which host is associated with the VM-host affinity policy.
.PARAMETER NumVms
Number of VMs associated with the VM-host affinity policy.
.PARAMETER NumHosts
Number of hosts associated with the VM-host affinity policy.
.PARAMETER NumCompliantVms
Number of VMs which are compliant with the VM-host affinity policy.
.PARAMETER NumNonCompliantVms
Number of VMs which are not compliant with the VM-host affinity policy.
.OUTPUTS

VmmV41AhvPoliciesVmHostAffinityPolicy<PSCustomObject>
#>

function Initialize-VmmV41AhvPoliciesVmHostAffinityPolicy {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${TenantId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ExtId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Links},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${CreateTime},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${UpdateTime},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CreatedBy},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${LastUpdatedBy},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${VmCategories},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${HostCategories},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${NumVms},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${NumHosts},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${NumCompliantVms},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${NumNonCompliantVms}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvPoliciesVmHostAffinityPolicy' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Links -and $Links.length -gt 20) {
            throw "invalid value for 'Links', number of items must be less than or equal to 20."
        }

        if (!$Links -and $Links.length -lt 0) {
            throw "invalid value for 'Links', number of items must be greater than or equal to 0."
        }

        if (!$Name -and $Name.length -gt 80) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 80."
        }

        if (!$VmCategories -and $VmCategories.length -gt 50) {
            throw "invalid value for 'VmCategories', number of items must be less than or equal to 50."
        }

        if (!$VmCategories -and $VmCategories.length -lt 1) {
            throw "invalid value for 'VmCategories', number of items must be greater than or equal to 1."
        }

        if (!$HostCategories -and $HostCategories.length -gt 50) {
            throw "invalid value for 'HostCategories', number of items must be less than or equal to 50."
        }

        if (!$HostCategories -and $HostCategories.length -lt 1) {
            throw "invalid value for 'HostCategories', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "name" = ${Name}
            "description" = ${Description}
            "createTime" = ${CreateTime}
            "updateTime" = ${UpdateTime}
            "createdBy" = ${CreatedBy}
            "lastUpdatedBy" = ${LastUpdatedBy}
            "vmCategories" = ${VmCategories}
            "hostCategories" = ${HostCategories}
            "numVms" = ${NumVms}
            "numHosts" = ${NumHosts}
            "numCompliantVms" = ${NumCompliantVms}
            "numNonCompliantVms" = ${NumNonCompliantVms}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvPoliciesVmHostAffinityPolicy<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvPoliciesVmHostAffinityPolicy<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvPoliciesVmHostAffinityPolicy<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvPoliciesVmHostAffinityPolicy {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvPoliciesVmHostAffinityPolicy' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvPoliciesVmHostAffinityPolicy
        $AllProperties = ("tenantId", "extId", "links", "name", "description", "createTime", "updateTime", "createdBy", "lastUpdatedBy", "vmCategories", "hostCategories", "numVms", "numHosts", "numCompliantVms", "numNonCompliantVms")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extId"))) { #optional property not found
            $ExtId = $null
        } else {
            $ExtId = $JsonParameters.PSobject.Properties["extId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "links"))) { #optional property not found
            $Links = $null
        } else {
            $Links = $JsonParameters.PSobject.Properties["links"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createTime"))) { #optional property not found
            $CreateTime = $null
        } else {
            $CreateTime = $JsonParameters.PSobject.Properties["createTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updateTime"))) { #optional property not found
            $UpdateTime = $null
        } else {
            $UpdateTime = $JsonParameters.PSobject.Properties["updateTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createdBy"))) { #optional property not found
            $CreatedBy = $null
        } else {
            $CreatedBy = $JsonParameters.PSobject.Properties["createdBy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastUpdatedBy"))) { #optional property not found
            $LastUpdatedBy = $null
        } else {
            $LastUpdatedBy = $JsonParameters.PSobject.Properties["lastUpdatedBy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vmCategories"))) { #optional property not found
            $VmCategories = $null
        } else {
            $VmCategories = $JsonParameters.PSobject.Properties["vmCategories"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hostCategories"))) { #optional property not found
            $HostCategories = $null
        } else {
            $HostCategories = $JsonParameters.PSobject.Properties["hostCategories"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numVms"))) { #optional property not found
            $NumVms = $null
        } else {
            $NumVms = $JsonParameters.PSobject.Properties["numVms"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numHosts"))) { #optional property not found
            $NumHosts = $null
        } else {
            $NumHosts = $JsonParameters.PSobject.Properties["numHosts"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numCompliantVms"))) { #optional property not found
            $NumCompliantVms = $null
        } else {
            $NumCompliantVms = $JsonParameters.PSobject.Properties["numCompliantVms"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numNonCompliantVms"))) { #optional property not found
            $NumNonCompliantVms = $null
        } else {
            $NumNonCompliantVms = $JsonParameters.PSobject.Properties["numNonCompliantVms"].value
        }

        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "name" = ${Name}
            "description" = ${Description}
            "createTime" = ${CreateTime}
            "updateTime" = ${UpdateTime}
            "createdBy" = ${CreatedBy}
            "lastUpdatedBy" = ${LastUpdatedBy}
            "vmCategories" = ${VmCategories}
            "hostCategories" = ${HostCategories}
            "numVms" = ${NumVms}
            "numHosts" = ${NumHosts}
            "numCompliantVms" = ${NumCompliantVms}
            "numNonCompliantVms" = ${NumNonCompliantVms}
        }

        return $PSO
    }

}

