#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The references to Prism Element cluster and respective retained images.

.PARAMETER ClusterExtId
Cluster external identifier.
.PARAMETER ImagesExtIds
List of external identifiers for images that need to be imported.
.OUTPUTS

VmmV41ContentImageImportConfig<PSCustomObject>
#>

function Initialize-VmmV41ContentImageImportConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ClusterExtId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${ImagesExtIds}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41ContentImageImportConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ClusterExtId) {
            throw "invalid value for 'ClusterExtId', 'ClusterExtId' cannot be null."
        }

        if ($null -eq $ImagesExtIds) {
            throw "invalid value for 'ImagesExtIds', 'ImagesExtIds' cannot be null."
        }

        if ($ImagesExtIds.length -gt 100) {
            throw "invalid value for 'ImagesExtIds', number of items must be less than or equal to 100."
        }

        if ($ImagesExtIds.length -lt 0) {
            throw "invalid value for 'ImagesExtIds', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "clusterExtId" = ${ClusterExtId}
            "imagesExtIds" = ${ImagesExtIds}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41ContentImageImportConfig<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41ContentImageImportConfig<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41ContentImageImportConfig<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41ContentImageImportConfig {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41ContentImageImportConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41ContentImageImportConfig
        $AllProperties = ("clusterExtId", "imagesExtIds")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'clusterExtId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "clusterExtId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'clusterExtId' missing."
        } else {
            $ClusterExtId = $JsonParameters.PSobject.Properties["clusterExtId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "imagesExtIds"))) {
            throw "Error! JSON cannot be serialized due to the required property 'imagesExtIds' missing."
        } else {
            $ImagesExtIds = $JsonParameters.PSobject.Properties["imagesExtIds"].value
        }

        $PSO = [PSCustomObject]@{
            "clusterExtId" = ${ClusterExtId}
            "imagesExtIds" = ${ImagesExtIds}
        }

        return $PSO
    }

}

