#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The (S)egment:(B)us:(D)evice.(F)unction hardware address. See https://wiki.xen.org/wiki/Bus:Device.Function_(BDF)_Notation for more details.

.PARAMETER Segment
PCI Segment.
.PARAMETER Bus
PCI Bus number in hexadecimal, often padded using a leading zeros to two or four digits.
.PARAMETER Device
PCI Device number in hexadecimal, often padded using a leading zero to two digits . Sometimes this is also referred to as the slot number.
.PARAMETER Func
PCI Function number in hexadecimal.
.OUTPUTS

VmmV41AhvConfigSBDF<PSCustomObject>
#>

function Initialize-VmmV41AhvConfigSBDF {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Segment},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Bus},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Device},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Func}
    )

    Process {
        'Creating PSCustomObject: vmm => VmmV41AhvConfigSBDF' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "segment" = ${Segment}
            "bus" = ${Bus}
            "device" = ${Device}
            "func" = ${Func}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigSBDF<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigSBDF<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigSBDF<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvConfigSBDF {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: vmm => VmmV41AhvConfigSBDF' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VmmV41AhvConfigSBDF
        $AllProperties = ("segment", "bus", "device", "func")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "segment"))) { #optional property not found
            $Segment = $null
        } else {
            $Segment = $JsonParameters.PSobject.Properties["segment"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bus"))) { #optional property not found
            $Bus = $null
        } else {
            $Bus = $JsonParameters.PSobject.Properties["bus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "device"))) { #optional property not found
            $Device = $null
        } else {
            $Device = $JsonParameters.PSobject.Properties["device"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "func"))) { #optional property not found
            $Func = $null
        } else {
            $Func = $JsonParameters.PSobject.Properties["func"].value
        }

        $PSO = [PSCustomObject]@{
            "segment" = ${Segment}
            "bus" = ${Bus}
            "device" = ${Device}
            "func" = ${Func}
        }

        return $PSO
    }

}

