#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum VmmV41AhvConfigCpuFeature.

.DESCRIPTION

The list of additional CPU features to be enabled.
#>

enum VmmV41AhvConfigCpuFeature {
    # enum value: "HARDWARE_VIRTUALIZATION"
    HARDWARE_VIRTUALIZATION
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

