#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

NIC configuration input for the restored VM. If not specified, the NICs in the VM Recovery Point will be restored.

.PARAMETER NicRemoveList
List of NIC UUIDs from the VM Recovery Point to be dropped when restoring the VM.
.PARAMETER NicOverrideList
List of NIC parameters to override the corresponding NICs captured in the VM Recovery Point. NIC external identifiers are utilized to map the NICs in this list to the NICs from the VM Recovery Point
.OUTPUTS

VmmV41AhvConfigVmRestoreNicConfigSpecification<PSCustomObject>
#>

function Initialize-VmmV41AhvConfigVmRestoreNicConfigSpecification {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${NicRemoveList},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${NicOverrideList}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigVmRestoreNicConfigSpecification' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$NicRemoveList -and $NicRemoveList.length -gt 64) {
            throw "invalid value for 'NicRemoveList', number of items must be less than or equal to 64."
        }

        if (!$NicRemoveList -and $NicRemoveList.length -lt 0) {
            throw "invalid value for 'NicRemoveList', number of items must be greater than or equal to 0."
        }

        if (!$NicOverrideList -and $NicOverrideList.length -gt 64) {
            throw "invalid value for 'NicOverrideList', number of items must be less than or equal to 64."
        }

        if (!$NicOverrideList -and $NicOverrideList.length -lt 0) {
            throw "invalid value for 'NicOverrideList', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "nicRemoveList" = ${NicRemoveList}
            "nicOverrideList" = ${NicOverrideList}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigVmRestoreNicConfigSpecification<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigVmRestoreNicConfigSpecification<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigVmRestoreNicConfigSpecification<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvConfigVmRestoreNicConfigSpecification {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigVmRestoreNicConfigSpecification' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvConfigVmRestoreNicConfigSpecification
        $AllProperties = ("nicRemoveList", "nicOverrideList")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nicRemoveList"))) { #optional property not found
            $NicRemoveList = $null
        } else {
            $NicRemoveList = $JsonParameters.PSobject.Properties["nicRemoveList"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nicOverrideList"))) { #optional property not found
            $NicOverrideList = $null
        } else {
            $NicOverrideList = $JsonParameters.PSobject.Properties["nicOverrideList"].value
        }

        $PSO = [PSCustomObject]@{
            "nicRemoveList" = ${NicRemoveList}
            "nicOverrideList" = ${NicOverrideList}
        }

        return $PSO
    }

}

