#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

URL to create an OVA.

.PARAMETER Url
The URL that can be used to download an OVA.
.PARAMETER ShouldAllowInsecureUrl
Ignore the certificate errors if the value is true. Default is false.
.PARAMETER BasicAuth
No description available.
.OUTPUTS

VmmV41ContentOvaUrlSource<PSCustomObject>
#>

function Initialize-VmmV41ContentOvaUrlSource {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^((http[s]?|nfs):/)?/?([^:/\s]*)((/\w+)*(:[0-9]+)*?/)([\w\-\.]+[^#?\s]+)(.*)?(#[\w\-]+)?$")]
        [String]
        ${Url},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ShouldAllowInsecureUrl} = $false,
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${BasicAuth}
    )

    Process {
        'Creating PSCustomObject: vmm => VmmV41ContentOvaUrlSource' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Url) {
            throw "invalid value for 'Url', 'Url' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "url" = ${Url}
            "shouldAllowInsecureUrl" = ${ShouldAllowInsecureUrl}
            "basicAuth" = ${BasicAuth}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41ContentOvaUrlSource<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41ContentOvaUrlSource<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41ContentOvaUrlSource<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41ContentOvaUrlSource {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: vmm => VmmV41ContentOvaUrlSource' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VmmV41ContentOvaUrlSource
        $AllProperties = ("url", "shouldAllowInsecureUrl", "basicAuth")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'url' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "url"))) {
            throw "Error! JSON cannot be serialized due to the required property 'url' missing."
        } else {
            $Url = $JsonParameters.PSobject.Properties["url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shouldAllowInsecureUrl"))) { #optional property not found
            $ShouldAllowInsecureUrl = $null
        } else {
            $ShouldAllowInsecureUrl = $JsonParameters.PSobject.Properties["shouldAllowInsecureUrl"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "basicAuth"))) { #optional property not found
            $BasicAuth = $null
        } else {
            $BasicAuth = $JsonParameters.PSobject.Properties["basicAuth"].value
        }

        $PSO = [PSCustomObject]@{
            "url" = ${Url}
            "shouldAllowInsecureUrl" = ${ShouldAllowInsecureUrl}
            "basicAuth" = ${BasicAuth}
        }

        return $PSO
    }

}

