#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Virtual Machine CD-ROM.

.PARAMETER BackingInfo
No description available.
.OUTPUTS

VmmV41AhvConfigCdRomInsertParams<PSCustomObject>
#>

function Initialize-VmmV41AhvConfigCdRomInsertParams {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${BackingInfo}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigCdRomInsertParams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "backingInfo" = ${BackingInfo}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigCdRomInsertParams<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigCdRomInsertParams<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigCdRomInsertParams<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvConfigCdRomInsertParams {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41AhvConfigCdRomInsertParams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41AhvConfigCdRomInsertParams
        $AllProperties = ("backingInfo")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "backingInfo"))) { #optional property not found
            $BackingInfo = $null
        } else {
            $BackingInfo = $JsonParameters.PSobject.Properties["backingInfo"].value
        }

        $PSO = [PSCustomObject]@{
            "backingInfo" = ${BackingInfo}
        }

        return $PSO
    }

}

