#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

List of categories to be associated to the VM.

.PARAMETER Categories
No description available.
.OUTPUTS

VmmV41EsxiConfigAssociateVmCategoriesParams<PSCustomObject>
#>

function Initialize-VmmV41EsxiConfigAssociateVmCategoriesParams {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Categories}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiConfigAssociateVmCategoriesParams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Categories) {
            throw "invalid value for 'Categories', 'Categories' cannot be null."
        }

        if ($Categories.length -gt 256) {
            throw "invalid value for 'Categories', number of items must be less than or equal to 256."
        }

        if ($Categories.length -lt 1) {
            throw "invalid value for 'Categories', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "categories" = ${Categories}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41EsxiConfigAssociateVmCategoriesParams<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41EsxiConfigAssociateVmCategoriesParams<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41EsxiConfigAssociateVmCategoriesParams<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41EsxiConfigAssociateVmCategoriesParams {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.vmm => NtnxV4VmmV41EsxiConfigAssociateVmCategoriesParams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4VmmV41EsxiConfigAssociateVmCategoriesParams
        $AllProperties = ("categories")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'categories' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "categories"))) {
            throw "Error! JSON cannot be serialized due to the required property 'categories' missing."
        } else {
            $Categories = $JsonParameters.PSobject.Properties["categories"].value
        }

        $PSO = [PSCustomObject]@{
            "categories" = ${Categories}
        }

        return $PSO
    }

}

