#
# Nutanix Virtual Machine Management APIs
# Manage the life-cycle of virtual machines hosted on Nutanix
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The disk migration plan defines how disks are migrated.

.PARAMETER StorageContainer
No description available.
.PARAMETER VmDisks
The disks included in the migration plan.
.OUTPUTS

VmmV41AhvConfigADSFDiskMigrationPlan<PSCustomObject>
#>

function Initialize-VmmV41AhvConfigADSFDiskMigrationPlan {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${StorageContainer},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${VmDisks}
    )

    Process {
        'Creating PSCustomObject: vmm => VmmV41AhvConfigADSFDiskMigrationPlan' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$VmDisks -and $VmDisks.length -gt 1034) {
            throw "invalid value for 'VmDisks', number of items must be less than or equal to 1034."
        }

        if (!$VmDisks -and $VmDisks.length -lt 0) {
            throw "invalid value for 'VmDisks', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "storageContainer" = ${StorageContainer}
            "vmDisks" = ${VmDisks}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VmmV41AhvConfigADSFDiskMigrationPlan<PSCustomObject>

.DESCRIPTION

Convert from JSON to VmmV41AhvConfigADSFDiskMigrationPlan<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VmmV41AhvConfigADSFDiskMigrationPlan<PSCustomObject>
#>
function ConvertFrom-JsonToVmmV41AhvConfigADSFDiskMigrationPlan {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: vmm => VmmV41AhvConfigADSFDiskMigrationPlan' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VmmV41AhvConfigADSFDiskMigrationPlan
        $AllProperties = ("storageContainer", "vmDisks")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "storageContainer"))) { #optional property not found
            $StorageContainer = $null
        } else {
            $StorageContainer = $JsonParameters.PSobject.Properties["storageContainer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vmDisks"))) { #optional property not found
            $VmDisks = $null
        } else {
            $VmDisks = $JsonParameters.PSobject.Properties["vmDisks"].value
        }

        $PSO = [PSCustomObject]@{
            "storageContainer" = ${StorageContainer}
            "vmDisks" = ${VmDisks}
        }

        return $PSO
    }

}

