#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Cluster Configuration required for a cluster to function properly.

.PARAMETER ShouldEnableLockdownMode
A boolean value indicating whether to enable lockdown mode for a cluster.
.PARAMETER BuildInfo
No description available.
.OUTPUTS

ClustermgmtV41ConfigClusterConfig<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigClusterConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ShouldEnableLockdownMode},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${BuildInfo}
    )

    Process {
        'Creating PSCustomObject: prism => ClustermgmtV41ConfigClusterConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "shouldEnableLockdownMode" = ${ShouldEnableLockdownMode}
            "buildInfo" = ${BuildInfo}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigClusterConfig<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigClusterConfig<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigClusterConfig<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigClusterConfig {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: prism => ClustermgmtV41ConfigClusterConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigClusterConfig
        $AllProperties = ("shouldEnableLockdownMode", "buildInfo")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shouldEnableLockdownMode"))) { #optional property not found
            $ShouldEnableLockdownMode = $null
        } else {
            $ShouldEnableLockdownMode = $JsonParameters.PSobject.Properties["shouldEnableLockdownMode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "buildInfo"))) { #optional property not found
            $BuildInfo = $null
        } else {
            $BuildInfo = $JsonParameters.PSobject.Properties["buildInfo"].value
        }

        $PSO = [PSCustomObject]@{
            "shouldEnableLockdownMode" = ${ShouldEnableLockdownMode}
            "buildInfo" = ${BuildInfo}
        }

        return $PSO
    }

}

