#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

This schema is generated from SchemaValidationError.java

.PARAMETER Timestamp
Timestamp of the response.
.PARAMETER StatusCode
The HTTP status code of the response.
.PARAMETER VarError
The generic error message for the response.
.PARAMETER Path
API path on which the request was made.
.PARAMETER ValidationErrorMessages
List of validation error messages
.OUTPUTS

PrismV41ErrorSchemaValidationError<PSCustomObject>
#>

function Initialize-PrismV41ErrorSchemaValidationError {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${StatusCode},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VarError},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Path},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ValidationErrorMessages}
    )

    Process {
        'Creating PSCustomObject: prism => PrismV41ErrorSchemaValidationError' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "timestamp" = ${Timestamp}
            "statusCode" = ${StatusCode}
            "error" = ${VarError}
            "path" = ${Path}
            "validationErrorMessages" = ${ValidationErrorMessages}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PrismV41ErrorSchemaValidationError<PSCustomObject>

.DESCRIPTION

Convert from JSON to PrismV41ErrorSchemaValidationError<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PrismV41ErrorSchemaValidationError<PSCustomObject>
#>
function ConvertFrom-JsonToPrismV41ErrorSchemaValidationError {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: prism => PrismV41ErrorSchemaValidationError' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PrismV41ErrorSchemaValidationError
        $AllProperties = ("timestamp", "statusCode", "error", "path", "validationErrorMessages")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "statusCode"))) { #optional property not found
            $StatusCode = $null
        } else {
            $StatusCode = $JsonParameters.PSobject.Properties["statusCode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "error"))) { #optional property not found
            $VarError = $null
        } else {
            $VarError = $JsonParameters.PSobject.Properties["error"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "path"))) { #optional property not found
            $Path = $null
        } else {
            $Path = $JsonParameters.PSobject.Properties["path"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "validationErrorMessages"))) { #optional property not found
            $ValidationErrorMessages = $null
        } else {
            $ValidationErrorMessages = $JsonParameters.PSobject.Properties["validationErrorMessages"].value
        }

        $PSO = [PSCustomObject]@{
            "timestamp" = ${Timestamp}
            "statusCode" = ${StatusCode}
            "error" = ${VarError}
            "path" = ${Path}
            "validationErrorMessages" = ${ValidationErrorMessages}
        }

        return $PSO
    }

}

