#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum PrismV41ConfigResourceType.

.DESCRIPTION

An enum denoting the associated resource types.<br> Resource types are further grouped into two types: entity or policy. 
#>

enum PrismV41ConfigResourceType {
    # enum value: "VM"
    VM
    # enum value: "MH_VM"
    MH_VM
    # enum value: "IMAGE"
    IMAGE
    # enum value: "SUBNET"
    SUBNET
    # enum value: "CLUSTER"
    CLUSTER
    # enum value: "HOST"
    HOST
    # enum value: "REPORT"
    REPORT
    # enum value: "MARKETPLACE_ITEM"
    MARKETPLACE_ITEM
    # enum value: "BLUEPRINT"
    BLUEPRINT
    # enum value: "APP"
    APP
    # enum value: "VOLUMEGROUP"
    VOLUMEGROUP
    # enum value: "IMAGE_PLACEMENT_POLICY"
    IMAGE_PLACEMENT_POLICY
    # enum value: "NETWORK_SECURITY_POLICY"
    NETWORK_SECURITY_POLICY
    # enum value: "NETWORK_SECURITY_RULE"
    NETWORK_SECURITY_RULE
    # enum value: "VM_HOST_AFFINITY_POLICY"
    VM_HOST_AFFINITY_POLICY
    # enum value: "VM_VM_ANTI_AFFINITY_POLICY"
    VM_VM_ANTI_AFFINITY_POLICY
    # enum value: "TEMPLATE_PLACEMENT_POLICY"
    TEMPLATE_PLACEMENT_POLICY
    # enum value: "QOS_POLICY"
    QOS_POLICY
    # enum value: "NGT_POLICY"
    NGT_POLICY
    # enum value: "PROTECTION_RULE"
    PROTECTION_RULE
    # enum value: "ACCESS_CONTROL_POLICY"
    ACCESS_CONTROL_POLICY
    # enum value: "STORAGE_POLICY"
    STORAGE_POLICY
    # enum value: "IMAGE_RATE_LIMIT"
    IMAGE_RATE_LIMIT
    # enum value: "RECOVERY_PLAN"
    RECOVERY_PLAN
    # enum value: "BUNDLE"
    BUNDLE
    # enum value: "POLICY_SCHEMA"
    POLICY_SCHEMA
    # enum value: "HOST_NIC"
    HOST_NIC
    # enum value: "ACTION_RULE"
    ACTION_RULE
    # enum value: "VIRTUAL_NIC"
    VIRTUAL_NIC
    # enum value: "VM_TEMPLATE"
    VM_TEMPLATE
    # enum value: "NETWORK_ENTITY_GROUP"
    NETWORK_ENTITY_GROUP
    # enum value: "VIRTUAL_NETWORK"
    VIRTUAL_NETWORK
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

