#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The success response that we want to return to the user. 

.PARAMETER Message
The success message field where the success response message will be put.
.OUTPUTS

PrismV41ProtectpcApiSuccess<PSCustomObject>
#>

function Initialize-NtnxV4PrismV41ProtectpcApiSuccess {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Message}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.prism => NtnxV4PrismV41ProtectpcApiSuccess' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "message" = ${Message}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PrismV41ProtectpcApiSuccess<PSCustomObject>

.DESCRIPTION

Convert from JSON to PrismV41ProtectpcApiSuccess<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PrismV41ProtectpcApiSuccess<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToPrismV41ProtectpcApiSuccess {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.prism => NtnxV4PrismV41ProtectpcApiSuccess' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4PrismV41ProtectpcApiSuccess
        $AllProperties = ("message")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "message"))) { #optional property not found
            $Message = $null
        } else {
            $Message = $JsonParameters.PSobject.Properties["message"].value
        }

        $PSO = [PSCustomObject]@{
            "message" = ${Message}
        }

        return $PSO
    }

}

