#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

An object containing a list of eligible cluster object. These are the eligible cluster for which PC backup is possible. 

.PARAMETER EligibleClusterList
No description available.
.OUTPUTS

PrismV41ProtectpcEligibleClusterList<PSCustomObject>
#>

function Initialize-PrismV41ProtectpcEligibleClusterList {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${EligibleClusterList}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.prism => NtnxV4PrismV41ProtectpcEligibleClusterList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "eligibleClusterList" = ${EligibleClusterList}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PrismV41ProtectpcEligibleClusterList<PSCustomObject>

.DESCRIPTION

Convert from JSON to PrismV41ProtectpcEligibleClusterList<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PrismV41ProtectpcEligibleClusterList<PSCustomObject>
#>
function ConvertFrom-JsonToPrismV41ProtectpcEligibleClusterList {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.prism => NtnxV4PrismV41ProtectpcEligibleClusterList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4PrismV41ProtectpcEligibleClusterList
        $AllProperties = ("eligibleClusterList")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "eligibleClusterList"))) { #optional property not found
            $EligibleClusterList = $null
        } else {
            $EligibleClusterList = $JsonParameters.PSobject.Properties["eligibleClusterList"].value
        }

        $PSO = [PSCustomObject]@{
            "eligibleClusterList" = ${EligibleClusterList}
        }

        return $PSO
    }

}

