#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The input specification for performing the batch operation.

.PARAMETER Metadata
No description available.
.PARAMETER Payload
No description available.
.OUTPUTS

PrismV41OperationsBatchSpec<PSCustomObject>
#>

function Initialize-NtnxV4PrismV41OperationsBatchSpec {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Metadata},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Payload}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.prism => NtnxV4PrismV41OperationsBatchSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Payload -and $Payload.length -gt 500) {
            throw "invalid value for 'Payload', number of items must be less than or equal to 500."
        }

        if (!$Payload -and $Payload.length -lt 0) {
            throw "invalid value for 'Payload', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "metadata" = ${Metadata}
            "payload" = ${Payload}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PrismV41OperationsBatchSpec<PSCustomObject>

.DESCRIPTION

Convert from JSON to PrismV41OperationsBatchSpec<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PrismV41OperationsBatchSpec<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToPrismV41OperationsBatchSpec {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.prism => NtnxV4PrismV41OperationsBatchSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4PrismV41OperationsBatchSpec
        $AllProperties = ("metadata", "payload")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "metadata"))) { #optional property not found
            $Metadata = $null
        } else {
            $Metadata = $JsonParameters.PSobject.Properties["metadata"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "payload"))) { #optional property not found
            $Payload = $null
        } else {
            $Payload = $JsonParameters.PSobject.Properties["payload"].value
        }

        $PSO = [PSCustomObject]@{
            "metadata" = ${Metadata}
            "payload" = ${Payload}
        }

        return $PSO
    }

}

