#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A model that represents a Batch resource.

.PARAMETER TenantId
A globally unique identifier that represents the tenant that owns this entity. The system automatically assigns it, and it and is immutable from an API consumer perspective (some use cases may cause this ID to change - For instance, a use case may require the transfer of ownership of the entity, but these cases are handled automatically on the server). 
.PARAMETER ExtId
A globally unique identifier of an instance that is suitable for external consumption. 
.PARAMETER Links
A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource. 
.PARAMETER Name
An user friendly name of the batch.
.PARAMETER StartTime
The execution start time of the batch. The value will be in extended ISO-8601 format. For example, start time of 2022-04-23T01:23:45.678+09:00 would imply that the batch started execution at 1:23:45.678  on the 23rd of April 2022. Details around ISO-8601 format can be found at https://www.iso.org/standard/70907.html 
.PARAMETER EndTime
The completion time of the batch. The value will be in extended ISO-8601 format. For example, end time of 2022-04-23T01:23:45.678+09:00 would imply that the batch completed its execution at 1:23:45.678  on the 23rd of April 2022. Details around ISO-8601 format can be found at https://www.iso.org/standard/70907.html 
.PARAMETER Size
The total number of elements submitted for processing in the batch.
.PARAMETER SuccessCount
The total number of elements successfully processed in the batch.
.PARAMETER FailedCount
The total number of elements that failed to be processed in the batch.
.PARAMETER CompletionStatus
No description available.
.PARAMETER ExecutionStatus
No description available.
.PARAMETER ShouldStopOnError
A flag indicating whether the batch procession should halt or continue when an error response is received from the server during the execution of a batch chunk
.OUTPUTS

PrismV41OperationsBatch<PSCustomObject>
#>

function Initialize-PrismV41OperationsBatch {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${TenantId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ExtId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Links},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${StartTime},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${EndTime},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Size},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SuccessCount},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${FailedCount},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("SUCCEEDED", "FAILED", "PARTIALLY_SUCCEEDED", "CANCELLED", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${CompletionStatus},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("IN_PROGRESS", "COMPLETED", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${ExecutionStatus},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ShouldStopOnError}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.prism => NtnxV4PrismV41OperationsBatch' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Links -and $Links.length -gt 20) {
            throw "invalid value for 'Links', number of items must be less than or equal to 20."
        }

        if (!$Links -and $Links.length -lt 0) {
            throw "invalid value for 'Links', number of items must be greater than or equal to 0."
        }

        if (!$Name -and $Name.length -gt 256) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 256."
        }


        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "name" = ${Name}
            "startTime" = ${StartTime}
            "endTime" = ${EndTime}
            "size" = ${Size}
            "successCount" = ${SuccessCount}
            "failedCount" = ${FailedCount}
            "completionStatus" = ${CompletionStatus}
            "executionStatus" = ${ExecutionStatus}
            "shouldStopOnError" = ${ShouldStopOnError}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PrismV41OperationsBatch<PSCustomObject>

.DESCRIPTION

Convert from JSON to PrismV41OperationsBatch<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PrismV41OperationsBatch<PSCustomObject>
#>
function ConvertFrom-JsonToPrismV41OperationsBatch {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.prism => NtnxV4PrismV41OperationsBatch' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4PrismV41OperationsBatch
        $AllProperties = ("tenantId", "extId", "links", "name", "startTime", "endTime", "size", "successCount", "failedCount", "completionStatus", "executionStatus", "shouldStopOnError")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extId"))) { #optional property not found
            $ExtId = $null
        } else {
            $ExtId = $JsonParameters.PSobject.Properties["extId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "links"))) { #optional property not found
            $Links = $null
        } else {
            $Links = $JsonParameters.PSobject.Properties["links"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "startTime"))) { #optional property not found
            $StartTime = $null
        } else {
            $StartTime = $JsonParameters.PSobject.Properties["startTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "endTime"))) { #optional property not found
            $EndTime = $null
        } else {
            $EndTime = $JsonParameters.PSobject.Properties["endTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "size"))) { #optional property not found
            $Size = $null
        } else {
            $Size = $JsonParameters.PSobject.Properties["size"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "successCount"))) { #optional property not found
            $SuccessCount = $null
        } else {
            $SuccessCount = $JsonParameters.PSobject.Properties["successCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "failedCount"))) { #optional property not found
            $FailedCount = $null
        } else {
            $FailedCount = $JsonParameters.PSobject.Properties["failedCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "completionStatus"))) { #optional property not found
            $CompletionStatus = $null
        } else {
            $CompletionStatus = $JsonParameters.PSobject.Properties["completionStatus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "executionStatus"))) { #optional property not found
            $ExecutionStatus = $null
        } else {
            $ExecutionStatus = $JsonParameters.PSobject.Properties["executionStatus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shouldStopOnError"))) { #optional property not found
            $ShouldStopOnError = $null
        } else {
            $ShouldStopOnError = $JsonParameters.PSobject.Properties["shouldStopOnError"].value
        }

        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "name" = ${Name}
            "startTime" = ${StartTime}
            "endTime" = ${EndTime}
            "size" = ${Size}
            "successCount" = ${SuccessCount}
            "failedCount" = ${FailedCount}
            "completionStatus" = ${CompletionStatus}
            "executionStatus" = ${ExecutionStatus}
            "shouldStopOnError" = ${ShouldStopOnError}
        }

        return $PSO
    }

}

