#
# Nutanix Prism APIs
# Manage Tasks, Category Associations and Submit Batch Operations.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum PrismV41ProtectpcPcEndpointFlavour.

.DESCRIPTION

No description available.
#>

enum PrismV41ProtectpcPcEndpointFlavour {
    # enum value: "kS3"
    kS3
    # enum value: "kOBJECTS"
    kOBJECTS
    # enum value: "UNKNOWN"
    UNKNOWN
}

