#
# Nutanix Security APIs
# Manage security features, such as encryption, certificates, or platform hardening.
# Version: 4.0.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Credential
No description available.
.PARAMETER Address
No description available.
.PARAMETER Type
Pre-defined type of credential.
.OUTPUTS

SecurityV40ConfigVcenterCredential<PSCustomObject>
#>

function Initialize-NtnxV4SecurityV40ConfigVcenterCredential {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Credential},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Address},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.security => NtnxV4SecurityV40ConfigVcenterCredential' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Credential) {
            throw "invalid value for 'Credential', 'Credential' cannot be null."
        }

        if ($null -eq $Address) {
            throw "invalid value for 'Address', 'Address' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "credential" = ${Credential}
            "address" = ${Address}
            "type" = ${Type}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SecurityV40ConfigVcenterCredential<PSCustomObject>

.DESCRIPTION

Convert from JSON to SecurityV40ConfigVcenterCredential<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SecurityV40ConfigVcenterCredential<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToSecurityV40ConfigVcenterCredential {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.security => NtnxV4SecurityV40ConfigVcenterCredential' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4SecurityV40ConfigVcenterCredential
        $AllProperties = ("credential", "address", "type")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'credential' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "credential"))) {
            throw "Error! JSON cannot be serialized due to the required property 'credential' missing."
        } else {
            $Credential = $JsonParameters.PSobject.Properties["credential"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "address"))) {
            throw "Error! JSON cannot be serialized due to the required property 'address' missing."
        } else {
            $Address = $JsonParameters.PSobject.Properties["address"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        $PSO = [PSCustomObject]@{
            "credential" = ${Credential}
            "address" = ${Address}
            "type" = ${Type}
        }

        return $PSO
    }

}

