#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ClustermgmtV41AhvConfigPcieDeviceType.

.DESCRIPTION

Device type according to the PCI code and ID assignment specification
#>

enum ClustermgmtV41AhvConfigPcieDeviceType {
    # enum value: "MASS_STORAGE_CONTROLLER"
    MASS_STORAGE_CONTROLLER
    # enum value: "NETWORK_CONTROLLER"
    NETWORK_CONTROLLER
    # enum value: "DISPLAY_CONTROLLER"
    DISPLAY_CONTROLLER
    # enum value: "MULTIMEDIA_DEVICE"
    MULTIMEDIA_DEVICE
    # enum value: "MEMORY_CONTROLLER"
    MEMORY_CONTROLLER
    # enum value: "BRIDGE_DEVICE"
    BRIDGE_DEVICE
    # enum value: "SIMPLE_COMMUNICATION_CONTROLLER"
    SIMPLE_COMMUNICATION_CONTROLLER
    # enum value: "BASE_SYSTEM_PERIPHERAL"
    BASE_SYSTEM_PERIPHERAL
    # enum value: "INPUT_DEVICE"
    INPUT_DEVICE
    # enum value: "DOCKING_STATION"
    DOCKING_STATION
    # enum value: "PROCESSOR"
    PROCESSOR
    # enum value: "SERIAL_BUS_CONTROLLER"
    SERIAL_BUS_CONTROLLER
    # enum value: "WIRELESS_CONTROLLER"
    WIRELESS_CONTROLLER
    # enum value: "INTELLIGENT_IO_CONTROLLER"
    INTELLIGENT_IO_CONTROLLER
    # enum value: "SATELLITE_COMMUNICATION_CONTROLLER"
    SATELLITE_COMMUNICATION_CONTROLLER
    # enum value: "ENCRYPTION_DECRYPTION_CONTROLLER"
    ENCRYPTION_DECRYPTION_CONTROLLER
    # enum value: "DATA_ACQUISITION_AND_SIGNAL_PROCESSING_CONTROLLER"
    DATA_ACQUISITION_AND_SIGNAL_PROCESSING_CONTROLLER
    # enum value: "PROCESSING_ACCELERATOR"
    PROCESSING_ACCELERATOR
    # enum value: "NON_ESSENTIAL_INSTRUMENTATION"
    NON_ESSENTIAL_INSTRUMENTATION
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

