#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Task Response which is one of node-discovery, networking-details, hypervisor-upload, validate-bundle-info, non-compatible-cluster-reference  information.

.PARAMETER Json

JSON object

.OUTPUTS

ClustermgmtV41ConfigTaskResponseAllOfResponse<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigTaskResponseAllOfResponse {
    [CmdletBinding()]
    Param (
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        $match = 0
        $matchType = $null
        $matchInstance = $null

        # try to match ClustermgmtV41ConfigHypervisorUploadInfo defined in the oneOf schemas
        try {
            $matchInstance = ConvertFrom-JsonToClustermgmtV41ConfigHypervisorUploadInfo $Json

            foreach($property in $matchInstance.PsObject.Properties) {
                if ($null -ne $property.Value) {
                    $matchType = "ClustermgmtV41ConfigHypervisorUploadInfo"
                    $match++
                    break
                }
            }
        } catch {
            # fail to match the schema defined in oneOf, proceed to the next one
            Write-Debug "Failed to match 'ClustermgmtV41ConfigHypervisorUploadInfo' defined in oneOf (ClustermgmtV41ConfigTaskResponseAllOfResponse). Proceeding to the next one if any."
        }

        # try to match ClustermgmtV41ConfigNodeNetworkingDetails defined in the oneOf schemas
        try {
            $matchInstance = ConvertFrom-JsonToClustermgmtV41ConfigNodeNetworkingDetails $Json

            foreach($property in $matchInstance.PsObject.Properties) {
                if ($null -ne $property.Value) {
                    $matchType = "ClustermgmtV41ConfigNodeNetworkingDetails"
                    $match++
                    break
                }
            }
        } catch {
            # fail to match the schema defined in oneOf, proceed to the next one
            Write-Debug "Failed to match 'ClustermgmtV41ConfigNodeNetworkingDetails' defined in oneOf (ClustermgmtV41ConfigTaskResponseAllOfResponse). Proceeding to the next one if any."
        }

        # try to match ClustermgmtV41ConfigNonCompatibleClusterReference[] defined in the oneOf schemas
        try {
            $matchInstance = ConvertFrom-JsonToClustermgmtV41ConfigNonCompatibleClusterReference[] $Json

            foreach($property in $matchInstance.PsObject.Properties) {
                if ($null -ne $property.Value) {
                    $matchType = "ClustermgmtV41ConfigNonCompatibleClusterReference[]"
                    $match++
                    break
                }
            }
        } catch {
            # fail to match the schema defined in oneOf, proceed to the next one
            Write-Debug "Failed to match 'ClustermgmtV41ConfigNonCompatibleClusterReference[]' defined in oneOf (ClustermgmtV41ConfigTaskResponseAllOfResponse). Proceeding to the next one if any."
        }

        # try to match ClustermgmtV41ConfigUnconfigureNodeDetails defined in the oneOf schemas
        try {
            $matchInstance = ConvertFrom-JsonToClustermgmtV41ConfigUnconfigureNodeDetails $Json

            foreach($property in $matchInstance.PsObject.Properties) {
                if ($null -ne $property.Value) {
                    $matchType = "ClustermgmtV41ConfigUnconfigureNodeDetails"
                    $match++
                    break
                }
            }
        } catch {
            # fail to match the schema defined in oneOf, proceed to the next one
            Write-Debug "Failed to match 'ClustermgmtV41ConfigUnconfigureNodeDetails' defined in oneOf (ClustermgmtV41ConfigTaskResponseAllOfResponse). Proceeding to the next one if any."
        }

        # try to match ClustermgmtV41ConfigValidateBundleInfo defined in the oneOf schemas
        try {
            $matchInstance = ConvertFrom-JsonToClustermgmtV41ConfigValidateBundleInfo $Json

            foreach($property in $matchInstance.PsObject.Properties) {
                if ($null -ne $property.Value) {
                    $matchType = "ClustermgmtV41ConfigValidateBundleInfo"
                    $match++
                    break
                }
            }
        } catch {
            # fail to match the schema defined in oneOf, proceed to the next one
            Write-Debug "Failed to match 'ClustermgmtV41ConfigValidateBundleInfo' defined in oneOf (ClustermgmtV41ConfigTaskResponseAllOfResponse). Proceeding to the next one if any."
        }

        if ($match -gt 1) {
            throw "Error! The JSON payload matches more than one type defined in oneOf schemas ([ClustermgmtV41ConfigHypervisorUploadInfo, ClustermgmtV41ConfigNodeNetworkingDetails, ClustermgmtV41ConfigNonCompatibleClusterReference[], ClustermgmtV41ConfigUnconfigureNodeDetails, ClustermgmtV41ConfigValidateBundleInfo]). JSON Payload: $($Json)"
        } elseif ($match -eq 1) {
            return [PSCustomObject]@{
                "ActualType" = ${matchType}
                "ActualInstance" = ${matchInstance}
                "OneOfSchemas" = @("ClustermgmtV41ConfigHypervisorUploadInfo", "ClustermgmtV41ConfigNodeNetworkingDetails", "ClustermgmtV41ConfigNonCompatibleClusterReference[]", "ClustermgmtV41ConfigUnconfigureNodeDetails", "ClustermgmtV41ConfigValidateBundleInfo")
            }
        } else {
            throw "Error! The JSON payload doesn't matches any type defined in oneOf schemas ([ClustermgmtV41ConfigHypervisorUploadInfo, ClustermgmtV41ConfigNodeNetworkingDetails, ClustermgmtV41ConfigNonCompatibleClusterReference[], ClustermgmtV41ConfigUnconfigureNodeDetails, ClustermgmtV41ConfigValidateBundleInfo]). JSON Payload: $($Json)"
        }
    }
}

