#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Network information of HCI and SO nodes.

.PARAMETER Hci
Network information of HCI nodes.
.PARAMETER So
Network information of SO nodes.
.OUTPUTS

ClustermgmtV41ConfigNetworkInfo<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigNetworkInfo {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Hci},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${So}
    )

    Process {
        'Creating PSCustomObject: clustermgmt => ClustermgmtV41ConfigNetworkInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Hci -and $Hci.length -gt 1024) {
            throw "invalid value for 'Hci', number of items must be less than or equal to 1024."
        }

        if (!$Hci -and $Hci.length -lt 0) {
            throw "invalid value for 'Hci', number of items must be greater than or equal to 0."
        }

        if (!$So -and $So.length -gt 1024) {
            throw "invalid value for 'So', number of items must be less than or equal to 1024."
        }

        if (!$So -and $So.length -lt 0) {
            throw "invalid value for 'So', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "hci" = ${Hci}
            "so" = ${So}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigNetworkInfo<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigNetworkInfo<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigNetworkInfo<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigNetworkInfo {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: clustermgmt => ClustermgmtV41ConfigNetworkInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigNetworkInfo
        $AllProperties = ("hci", "so")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hci"))) { #optional property not found
            $Hci = $null
        } else {
            $Hci = $JsonParameters.PSobject.Properties["hci"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "so"))) { #optional property not found
            $So = $null
        } else {
            $So = $JsonParameters.PSobject.Properties["so"].value
        }

        $PSO = [PSCustomObject]@{
            "hci" = ${Hci}
            "so" = ${So}
        }

        return $PSO
    }

}

