#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ClustermgmtV41ConfigNsIpPoolType.

.DESCRIPTION

Type of IP Pool, whether the IP Pool was created on PC or PE.
#>

enum ClustermgmtV41ConfigNsIpPoolType {
    # enum value: "PE_IP_POOL"
    PE_IP_POOL
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

