#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TenantId
A globally unique identifier that represents the tenant that owns this entity. The system automatically assigns it, and it and is immutable from an API consumer perspective (some use cases may cause this ID to change - For instance, a use case may require the transfer of ownership of the entity, but these cases are handled automatically on the server). 
.PARAMETER ExtId
A globally unique identifier of an instance that is suitable for external consumption. 
.PARAMETER Links
A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource. 
.PARAMETER Name
Name of the cluster profile.
.PARAMETER Description
Detailed description of a cluster profile.
.PARAMETER CreateTime
Creation time of a cluster profile.
.PARAMETER LastUpdateTime
The last updated time of a cluster profile.
.PARAMETER CreatedBy
Details of the user who created the cluster profile.
.PARAMETER LastUpdatedBy
Details of the user who has recently updated the cluster profile.
.PARAMETER ClusterCount
Count of clusters associated to a cluster profile.
.PARAMETER DriftedClusterCount
The count indicates the number of clusters associated with a cluster profile that has experienced drift. Drifted clusters are those in which the configuration differs from the defined profile. For example, the NTP server has different values on a cluster as compared to the profile it is attached.
.PARAMETER Clusters
Managed cluster information.
.PARAMETER AllowedOverrides
Indicates if a configuration of attached clusters can be skipped from monitoring.
.PARAMETER NameServerIpList
List of name servers on a cluster. This is a part of payload for both clusters create and update operations. Currently, only IPv4 address and FQDN (fully qualified domain name) values are supported for the create operation.
.PARAMETER NtpServerIpList
List of NTP servers on a cluster. This is a part of payload for both cluster create and update operations. Currently, only IPv4 address and FQDN (fully qualified domain name) values are supported for the create operation.
.PARAMETER SmtpServer
No description available.
.PARAMETER NfsSubnetWhitelist
NFS subnet allowlist addresses. This is part of the payload for cluster update operation only.
.PARAMETER SnmpConfig
No description available.
.PARAMETER RsyslogServerList
RSYSLOG Server.
.PARAMETER PulseStatus
No description available.
.OUTPUTS

ClustermgmtV41ConfigClusterProfile<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigClusterProfile {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${TenantId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ExtId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Links},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[A-Za-z0-9._-]+$")]
        [String]
        ${Name},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${CreateTime},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${LastUpdateTime},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${CreatedBy},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${LastUpdatedBy},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${ClusterCount},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${DriftedClusterCount},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Clusters},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AllowedOverrides},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${NameServerIpList},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${NtpServerIpList},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SmtpServer},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${NfsSubnetWhitelist},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SnmpConfig},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${RsyslogServerList},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${PulseStatus}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigClusterProfile' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Links -and $Links.length -gt 20) {
            throw "invalid value for 'Links', number of items must be less than or equal to 20."
        }

        if (!$Links -and $Links.length -lt 0) {
            throw "invalid value for 'Links', number of items must be greater than or equal to 0."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($Name.length -gt 64) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 64."
        }

        if (!$Description -and $Description.length -gt 1000) {
            throw "invalid value for 'Description', the character length must be smaller than or equal to 1000."
        }

        if (!$Clusters -and $Clusters.length -gt 400) {
            throw "invalid value for 'Clusters', number of items must be less than or equal to 400."
        }

        if (!$Clusters -and $Clusters.length -lt 1) {
            throw "invalid value for 'Clusters', number of items must be greater than or equal to 1."
        }

        if (!$AllowedOverrides -and $AllowedOverrides.length -gt 50) {
            throw "invalid value for 'AllowedOverrides', number of items must be less than or equal to 50."
        }

        if (!$AllowedOverrides -and $AllowedOverrides.length -lt 0) {
            throw "invalid value for 'AllowedOverrides', number of items must be greater than or equal to 0."
        }

        if (!$NameServerIpList -and $NameServerIpList.length -gt 1024) {
            throw "invalid value for 'NameServerIpList', number of items must be less than or equal to 1024."
        }

        if (!$NameServerIpList -and $NameServerIpList.length -lt 0) {
            throw "invalid value for 'NameServerIpList', number of items must be greater than or equal to 0."
        }

        if (!$NtpServerIpList -and $NtpServerIpList.length -gt 1024) {
            throw "invalid value for 'NtpServerIpList', number of items must be less than or equal to 1024."
        }

        if (!$NtpServerIpList -and $NtpServerIpList.length -lt 0) {
            throw "invalid value for 'NtpServerIpList', number of items must be greater than or equal to 0."
        }

        if (!$NfsSubnetWhitelist -and $NfsSubnetWhitelist.length -gt 1024) {
            throw "invalid value for 'NfsSubnetWhitelist', number of items must be less than or equal to 1024."
        }

        if (!$NfsSubnetWhitelist -and $NfsSubnetWhitelist.length -lt 0) {
            throw "invalid value for 'NfsSubnetWhitelist', number of items must be greater than or equal to 0."
        }

        if (!$RsyslogServerList -and $RsyslogServerList.length -gt 100) {
            throw "invalid value for 'RsyslogServerList', number of items must be less than or equal to 100."
        }

        if (!$RsyslogServerList -and $RsyslogServerList.length -lt 0) {
            throw "invalid value for 'RsyslogServerList', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "name" = ${Name}
            "description" = ${Description}
            "createTime" = ${CreateTime}
            "lastUpdateTime" = ${LastUpdateTime}
            "createdBy" = ${CreatedBy}
            "lastUpdatedBy" = ${LastUpdatedBy}
            "clusterCount" = ${ClusterCount}
            "driftedClusterCount" = ${DriftedClusterCount}
            "clusters" = ${Clusters}
            "allowedOverrides" = ${AllowedOverrides}
            "nameServerIpList" = ${NameServerIpList}
            "ntpServerIpList" = ${NtpServerIpList}
            "smtpServer" = ${SmtpServer}
            "nfsSubnetWhitelist" = ${NfsSubnetWhitelist}
            "snmpConfig" = ${SnmpConfig}
            "rsyslogServerList" = ${RsyslogServerList}
            "pulseStatus" = ${PulseStatus}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigClusterProfile<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigClusterProfile<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigClusterProfile<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigClusterProfile {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigClusterProfile' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigClusterProfile
        $AllProperties = ("tenantId", "extId", "links", "name", "description", "createTime", "lastUpdateTime", "createdBy", "lastUpdatedBy", "clusterCount", "driftedClusterCount", "clusters", "allowedOverrides", "nameServerIpList", "ntpServerIpList", "smtpServer", "nfsSubnetWhitelist", "snmpConfig", "rsyslogServerList", "pulseStatus")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extId"))) { #optional property not found
            $ExtId = $null
        } else {
            $ExtId = $JsonParameters.PSobject.Properties["extId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "links"))) { #optional property not found
            $Links = $null
        } else {
            $Links = $JsonParameters.PSobject.Properties["links"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createTime"))) { #optional property not found
            $CreateTime = $null
        } else {
            $CreateTime = $JsonParameters.PSobject.Properties["createTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastUpdateTime"))) { #optional property not found
            $LastUpdateTime = $null
        } else {
            $LastUpdateTime = $JsonParameters.PSobject.Properties["lastUpdateTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createdBy"))) { #optional property not found
            $CreatedBy = $null
        } else {
            $CreatedBy = $JsonParameters.PSobject.Properties["createdBy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastUpdatedBy"))) { #optional property not found
            $LastUpdatedBy = $null
        } else {
            $LastUpdatedBy = $JsonParameters.PSobject.Properties["lastUpdatedBy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "clusterCount"))) { #optional property not found
            $ClusterCount = $null
        } else {
            $ClusterCount = $JsonParameters.PSobject.Properties["clusterCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "driftedClusterCount"))) { #optional property not found
            $DriftedClusterCount = $null
        } else {
            $DriftedClusterCount = $JsonParameters.PSobject.Properties["driftedClusterCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "clusters"))) { #optional property not found
            $Clusters = $null
        } else {
            $Clusters = $JsonParameters.PSobject.Properties["clusters"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "allowedOverrides"))) { #optional property not found
            $AllowedOverrides = $null
        } else {
            $AllowedOverrides = $JsonParameters.PSobject.Properties["allowedOverrides"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nameServerIpList"))) { #optional property not found
            $NameServerIpList = $null
        } else {
            $NameServerIpList = $JsonParameters.PSobject.Properties["nameServerIpList"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ntpServerIpList"))) { #optional property not found
            $NtpServerIpList = $null
        } else {
            $NtpServerIpList = $JsonParameters.PSobject.Properties["ntpServerIpList"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpServer"))) { #optional property not found
            $SmtpServer = $null
        } else {
            $SmtpServer = $JsonParameters.PSobject.Properties["smtpServer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nfsSubnetWhitelist"))) { #optional property not found
            $NfsSubnetWhitelist = $null
        } else {
            $NfsSubnetWhitelist = $JsonParameters.PSobject.Properties["nfsSubnetWhitelist"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "snmpConfig"))) { #optional property not found
            $SnmpConfig = $null
        } else {
            $SnmpConfig = $JsonParameters.PSobject.Properties["snmpConfig"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rsyslogServerList"))) { #optional property not found
            $RsyslogServerList = $null
        } else {
            $RsyslogServerList = $JsonParameters.PSobject.Properties["rsyslogServerList"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "pulseStatus"))) { #optional property not found
            $PulseStatus = $null
        } else {
            $PulseStatus = $JsonParameters.PSobject.Properties["pulseStatus"].value
        }

        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "name" = ${Name}
            "description" = ${Description}
            "createTime" = ${CreateTime}
            "lastUpdateTime" = ${LastUpdateTime}
            "createdBy" = ${CreatedBy}
            "lastUpdatedBy" = ${LastUpdatedBy}
            "clusterCount" = ${ClusterCount}
            "driftedClusterCount" = ${DriftedClusterCount}
            "clusters" = ${Clusters}
            "allowedOverrides" = ${AllowedOverrides}
            "nameServerIpList" = ${NameServerIpList}
            "ntpServerIpList" = ${NtpServerIpList}
            "smtpServer" = ${SmtpServer}
            "nfsSubnetWhitelist" = ${NfsSubnetWhitelist}
            "snmpConfig" = ${SnmpConfig}
            "rsyslogServerList" = ${RsyslogServerList}
            "pulseStatus" = ${PulseStatus}
        }

        return $PSO
    }

}

