#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Clusters
Cluster reference for an entity.
.OUTPUTS

ClustermgmtV41ConfigClusterReferenceListSpec<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigClusterReferenceListSpec {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Clusters}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigClusterReferenceListSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Clusters) {
            throw "invalid value for 'Clusters', 'Clusters' cannot be null."
        }

        if ($Clusters.length -gt 400) {
            throw "invalid value for 'Clusters', number of items must be less than or equal to 400."
        }

        if ($Clusters.length -lt 1) {
            throw "invalid value for 'Clusters', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "clusters" = ${Clusters}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigClusterReferenceListSpec<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigClusterReferenceListSpec<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigClusterReferenceListSpec<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigClusterReferenceListSpec {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigClusterReferenceListSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigClusterReferenceListSpec
        $AllProperties = ("clusters")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'clusters' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "clusters"))) {
            throw "Error! JSON cannot be serialized due to the required property 'clusters' missing."
        } else {
            $Clusters = $JsonParameters.PSobject.Properties["clusters"].value
        }

        $PSO = [PSCustomObject]@{
            "clusters" = ${Clusters}
        }

        return $PSO
    }

}

