#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Pulse status for a cluster.

.PARAMETER IsEnabled
Flag determines whether pulse is enabled for a cluster.
.PARAMETER PiiScrubbingLevel
No description available.
.OUTPUTS

ClustermgmtV41ConfigPulseStatus<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigPulseStatus {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsEnabled},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("DEFAULT", "ALL", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${PiiScrubbingLevel}
    )

    Process {
        'Creating PSCustomObject: clustermgmt => ClustermgmtV41ConfigPulseStatus' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "isEnabled" = ${IsEnabled}
            "piiScrubbingLevel" = ${PiiScrubbingLevel}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigPulseStatus<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigPulseStatus<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigPulseStatus<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigPulseStatus {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: clustermgmt => ClustermgmtV41ConfigPulseStatus' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigPulseStatus
        $AllProperties = ("isEnabled", "piiScrubbingLevel")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isEnabled"))) { #optional property not found
            $IsEnabled = $null
        } else {
            $IsEnabled = $JsonParameters.PSobject.Properties["isEnabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "piiScrubbingLevel"))) { #optional property not found
            $PiiScrubbingLevel = $null
        } else {
            $PiiScrubbingLevel = $JsonParameters.PSobject.Properties["piiScrubbingLevel"].value
        }

        $PSO = [PSCustomObject]@{
            "isEnabled" = ${IsEnabled}
            "piiScrubbingLevel" = ${PiiScrubbingLevel}
        }

        return $PSO
    }

}

