#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Network details of nodes.

.PARAMETER NetworkInfo
No description available.
.PARAMETER Uplinks
List of uplinks information for each CVM IP.
.PARAMETER Warnings
List of warning messages.
.OUTPUTS

ClustermgmtV41ConfigNodeNetworkingDetails<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigNodeNetworkingDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${NetworkInfo},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Uplinks},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Warnings}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigNodeNetworkingDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Uplinks -and $Uplinks.length -gt 1024) {
            throw "invalid value for 'Uplinks', number of items must be less than or equal to 1024."
        }

        if (!$Uplinks -and $Uplinks.length -lt 0) {
            throw "invalid value for 'Uplinks', number of items must be greater than or equal to 0."
        }

        if (!$Warnings -and $Warnings.length -gt 1024) {
            throw "invalid value for 'Warnings', number of items must be less than or equal to 1024."
        }

        if (!$Warnings -and $Warnings.length -lt 0) {
            throw "invalid value for 'Warnings', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "networkInfo" = ${NetworkInfo}
            "uplinks" = ${Uplinks}
            "warnings" = ${Warnings}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigNodeNetworkingDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigNodeNetworkingDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigNodeNetworkingDetails<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigNodeNetworkingDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigNodeNetworkingDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigNodeNetworkingDetails
        $AllProperties = ("networkInfo", "uplinks", "warnings")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "networkInfo"))) { #optional property not found
            $NetworkInfo = $null
        } else {
            $NetworkInfo = $JsonParameters.PSobject.Properties["networkInfo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "uplinks"))) { #optional property not found
            $Uplinks = $null
        } else {
            $Uplinks = $JsonParameters.PSobject.Properties["uplinks"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "warnings"))) { #optional property not found
            $Warnings = $null
        } else {
            $Warnings = $JsonParameters.PSobject.Properties["warnings"].value
        }

        $PSO = [PSCustomObject]@{
            "networkInfo" = ${NetworkInfo}
            "uplinks" = ${Uplinks}
            "warnings" = ${Warnings}
        }

        return $PSO
    }

}

