#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Details for recovering a faulted cluster.

.PARAMETER DestinationClusterExtId
The destination cluster UUID to recover the faulted cluster.
.OUTPUTS

ClustermgmtV41ConfigRecoverySpec<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigRecoverySpec {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${DestinationClusterExtId}
    )

    Process {
        'Creating PSCustomObject: clustermgmt => ClustermgmtV41ConfigRecoverySpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "destinationClusterExtId" = ${DestinationClusterExtId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigRecoverySpec<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigRecoverySpec<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigRecoverySpec<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigRecoverySpec {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: clustermgmt => ClustermgmtV41ConfigRecoverySpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigRecoverySpec
        $AllProperties = ("destinationClusterExtId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "destinationClusterExtId"))) { #optional property not found
            $DestinationClusterExtId = $null
        } else {
            $DestinationClusterExtId = $JsonParameters.PSobject.Properties["destinationClusterExtId"].value
        }

        $PSO = [PSCustomObject]@{
            "destinationClusterExtId" = ${DestinationClusterExtId}
        }

        return $PSO
    }

}

