#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Individual node item details for checking whether hypervisor ISO upload is required or not.

.PARAMETER NodeUuid
UUID of the host.
.PARAMETER HypervisorVersion
Host version of the node.
.PARAMETER NosVersion
NOS software version of a node.
.PARAMETER Model
Rackable unit model type.
.PARAMETER BlockId
Rackable unit Id in which node resides.
.PARAMETER IsLightCompute
Indicates whether the node is light compute or not.
.PARAMETER HypervisorType
No description available.
.PARAMETER IsRoboMixedHypervisor
Indicates whether the hypervisor is robo mixed or not.
.PARAMETER IsMinimumComputeNode
Indicates if node is minimum compute or not.
.PARAMETER LuksStatus
No description available.
.OUTPUTS

ClustermgmtV41ConfigHypervisorUploadNodeListItem<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigHypervisorUploadNodeListItem {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${NodeUuid},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HypervisorVersion},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NosVersion},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Model},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BlockId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsLightCompute},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("AHV", "ESX", "HYPERV", "XEN", "NATIVEHOST", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${HypervisorType},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsRoboMixedHypervisor},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsMinimumComputeNode},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("NON_LUKS", "LUKS", "PARTIAL_LUKS", "UNKNOWN_LUKS", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${LuksStatus}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigHypervisorUploadNodeListItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "nodeUuid" = ${NodeUuid}
            "hypervisorVersion" = ${HypervisorVersion}
            "nosVersion" = ${NosVersion}
            "model" = ${Model}
            "blockId" = ${BlockId}
            "isLightCompute" = ${IsLightCompute}
            "hypervisorType" = ${HypervisorType}
            "isRoboMixedHypervisor" = ${IsRoboMixedHypervisor}
            "isMinimumComputeNode" = ${IsMinimumComputeNode}
            "luksStatus" = ${LuksStatus}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigHypervisorUploadNodeListItem<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigHypervisorUploadNodeListItem<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigHypervisorUploadNodeListItem<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigHypervisorUploadNodeListItem {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigHypervisorUploadNodeListItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigHypervisorUploadNodeListItem
        $AllProperties = ("nodeUuid", "hypervisorVersion", "nosVersion", "model", "blockId", "isLightCompute", "hypervisorType", "isRoboMixedHypervisor", "isMinimumComputeNode", "luksStatus")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nodeUuid"))) { #optional property not found
            $NodeUuid = $null
        } else {
            $NodeUuid = $JsonParameters.PSobject.Properties["nodeUuid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hypervisorVersion"))) { #optional property not found
            $HypervisorVersion = $null
        } else {
            $HypervisorVersion = $JsonParameters.PSobject.Properties["hypervisorVersion"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nosVersion"))) { #optional property not found
            $NosVersion = $null
        } else {
            $NosVersion = $JsonParameters.PSobject.Properties["nosVersion"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "model"))) { #optional property not found
            $Model = $null
        } else {
            $Model = $JsonParameters.PSobject.Properties["model"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blockId"))) { #optional property not found
            $BlockId = $null
        } else {
            $BlockId = $JsonParameters.PSobject.Properties["blockId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isLightCompute"))) { #optional property not found
            $IsLightCompute = $null
        } else {
            $IsLightCompute = $JsonParameters.PSobject.Properties["isLightCompute"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hypervisorType"))) { #optional property not found
            $HypervisorType = $null
        } else {
            $HypervisorType = $JsonParameters.PSobject.Properties["hypervisorType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isRoboMixedHypervisor"))) { #optional property not found
            $IsRoboMixedHypervisor = $null
        } else {
            $IsRoboMixedHypervisor = $JsonParameters.PSobject.Properties["isRoboMixedHypervisor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isMinimumComputeNode"))) { #optional property not found
            $IsMinimumComputeNode = $null
        } else {
            $IsMinimumComputeNode = $JsonParameters.PSobject.Properties["isMinimumComputeNode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "luksStatus"))) { #optional property not found
            $LuksStatus = $null
        } else {
            $LuksStatus = $JsonParameters.PSobject.Properties["luksStatus"].value
        }

        $PSO = [PSCustomObject]@{
            "nodeUuid" = ${NodeUuid}
            "hypervisorVersion" = ${HypervisorVersion}
            "nosVersion" = ${NosVersion}
            "model" = ${Model}
            "blockId" = ${BlockId}
            "isLightCompute" = ${IsLightCompute}
            "hypervisorType" = ${HypervisorType}
            "isRoboMixedHypervisor" = ${IsRoboMixedHypervisor}
            "isMinimumComputeNode" = ${IsMinimumComputeNode}
            "luksStatus" = ${LuksStatus}
        }

        return $PSO
    }

}

