#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

HyperV Credentials.

.PARAMETER DomainDetails
No description available.
.PARAMETER FailoverClusterDetails
No description available.
.OUTPUTS

ClustermgmtV41ConfigHypervCredentials<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigHypervCredentials {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DomainDetails},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${FailoverClusterDetails}
    )

    Process {
        'Creating PSCustomObject: clustermgmt => ClustermgmtV41ConfigHypervCredentials' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "domainDetails" = ${DomainDetails}
            "failoverClusterDetails" = ${FailoverClusterDetails}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigHypervCredentials<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigHypervCredentials<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigHypervCredentials<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigHypervCredentials {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: clustermgmt => ClustermgmtV41ConfigHypervCredentials' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigHypervCredentials
        $AllProperties = ("domainDetails", "failoverClusterDetails")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "domainDetails"))) { #optional property not found
            $DomainDetails = $null
        } else {
            $DomainDetails = $JsonParameters.PSobject.Properties["domainDetails"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "failoverClusterDetails"))) { #optional property not found
            $FailoverClusterDetails = $null
        } else {
            $FailoverClusterDetails = $JsonParameters.PSobject.Properties["failoverClusterDetails"].value
        }

        $PSO = [PSCustomObject]@{
            "domainDetails" = ${DomainDetails}
            "failoverClusterDetails" = ${FailoverClusterDetails}
        }

        return $PSO
    }

}

