#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ClustermgmtV41ConfigStorageTierReference.

.DESCRIPTION

Disk storage Tier type.
#>

enum ClustermgmtV41ConfigStorageTierReference {
    # enum value: "PCIE_SSD"
    PCIE_SSD
    # enum value: "SATA_SSD"
    SATA_SSD
    # enum value: "HDD"
    HDD
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

