#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TenantId
A globally unique identifier that represents the tenant that owns this entity. The system automatically assigns it, and it and is immutable from an API consumer perspective (some use cases may cause this ID to change - For instance, a use case may require the transfer of ownership of the entity, but these cases are handled automatically on the server). 
.PARAMETER ExtId
A globally unique identifier of an instance that is suitable for external consumption. 
.PARAMETER Links
A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource. 
.PARAMETER DatastoreName
Name of the datastore.
.PARAMETER NodeExtIds
The UUIDs of the nodes where the NFS datastore has to be created.
.OUTPUTS

ClustermgmtV41ConfigDataStoreUnmount<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigDataStoreUnmount {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${TenantId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ExtId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Links},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DatastoreName},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${NodeExtIds}
    )

    Process {
        'Creating PSCustomObject: clustermgmt => ClustermgmtV41ConfigDataStoreUnmount' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Links -and $Links.length -gt 20) {
            throw "invalid value for 'Links', number of items must be less than or equal to 20."
        }

        if (!$Links -and $Links.length -lt 0) {
            throw "invalid value for 'Links', number of items must be greater than or equal to 0."
        }

        if ($null -eq $DatastoreName) {
            throw "invalid value for 'DatastoreName', 'DatastoreName' cannot be null."
        }

        if ($DatastoreName.length -gt 255) {
            throw "invalid value for 'DatastoreName', the character length must be smaller than or equal to 255."
        }

        if (!$NodeExtIds -and $NodeExtIds.length -gt 50) {
            throw "invalid value for 'NodeExtIds', number of items must be less than or equal to 50."
        }

        if (!$NodeExtIds -and $NodeExtIds.length -lt 0) {
            throw "invalid value for 'NodeExtIds', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "datastoreName" = ${DatastoreName}
            "nodeExtIds" = ${NodeExtIds}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigDataStoreUnmount<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigDataStoreUnmount<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigDataStoreUnmount<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigDataStoreUnmount {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: clustermgmt => ClustermgmtV41ConfigDataStoreUnmount' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClustermgmtV41ConfigDataStoreUnmount
        $AllProperties = ("tenantId", "extId", "links", "datastoreName", "nodeExtIds")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'datastoreName' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datastoreName"))) {
            throw "Error! JSON cannot be serialized due to the required property 'datastoreName' missing."
        } else {
            $DatastoreName = $JsonParameters.PSobject.Properties["datastoreName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extId"))) { #optional property not found
            $ExtId = $null
        } else {
            $ExtId = $JsonParameters.PSobject.Properties["extId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "links"))) { #optional property not found
            $Links = $null
        } else {
            $Links = $JsonParameters.PSobject.Properties["links"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nodeExtIds"))) { #optional property not found
            $NodeExtIds = $null
        } else {
            $NodeExtIds = $JsonParameters.PSobject.Properties["nodeExtIds"].value
        }

        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "datastoreName" = ${DatastoreName}
            "nodeExtIds" = ${NodeExtIds}
        }

        return $PSO
    }

}

