#
# Nutanix Security APIs
# Manage security features, such as encryption, certificates, or platform hardening.
# Version: 4.0.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

REST response for all response codes in API path /security/v4.0/management/approval-policies/{extId} Put operation

.PARAMETER Metadata
No description available.
.PARAMETER VarData
No description available.
.OUTPUTS

SecurityV40ManagementUpdateApprovalPolicyApiResponse<PSCustomObject>
#>

function Initialize-SecurityV40ManagementUpdateApprovalPolicyApiResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Metadata},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VarData}
    )

    Process {
        'Creating PSCustomObject: security => SecurityV40ManagementUpdateApprovalPolicyApiResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "metadata" = ${Metadata}
            "data" = ${VarData}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SecurityV40ManagementUpdateApprovalPolicyApiResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to SecurityV40ManagementUpdateApprovalPolicyApiResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SecurityV40ManagementUpdateApprovalPolicyApiResponse<PSCustomObject>
#>
function ConvertFrom-JsonToSecurityV40ManagementUpdateApprovalPolicyApiResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: security => SecurityV40ManagementUpdateApprovalPolicyApiResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SecurityV40ManagementUpdateApprovalPolicyApiResponse
        $AllProperties = ("metadata", "data")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "metadata"))) { #optional property not found
            $Metadata = $null
        } else {
            $Metadata = $JsonParameters.PSobject.Properties["metadata"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data"))) { #optional property not found
            $VarData = $null
        } else {
            $VarData = $JsonParameters.PSobject.Properties["data"].value
        }

        $PSO = [PSCustomObject]@{
            "metadata" = ${Metadata}
            "data" = ${VarData}
        }

        return $PSO
    }

}

