#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Managed cluster information.

.PARAMETER ExtId
Indicates the UUID of a cluster.
.PARAMETER IsCompliant
Indicates if the attached cluster is compliant with the cluster profile or not.
.PARAMETER LastSyncedTime
The most recent date and time when the cluster profile was monitored across all attached clusters.
.PARAMETER ConfigDrifts
Drifted settings information.
.OUTPUTS

ClustermgmtV41ConfigManagedCluster<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigManagedCluster {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ExtId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsCompliant},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${LastSyncedTime},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ConfigDrifts}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigManagedCluster' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ExtId) {
            throw "invalid value for 'ExtId', 'ExtId' cannot be null."
        }

        if (!$ConfigDrifts -and $ConfigDrifts.length -gt 50) {
            throw "invalid value for 'ConfigDrifts', number of items must be less than or equal to 50."
        }

        if (!$ConfigDrifts -and $ConfigDrifts.length -lt 0) {
            throw "invalid value for 'ConfigDrifts', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "extId" = ${ExtId}
            "isCompliant" = ${IsCompliant}
            "lastSyncedTime" = ${LastSyncedTime}
            "configDrifts" = ${ConfigDrifts}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigManagedCluster<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigManagedCluster<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigManagedCluster<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigManagedCluster {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigManagedCluster' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigManagedCluster
        $AllProperties = ("extId", "isCompliant", "lastSyncedTime", "configDrifts")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'extId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'extId' missing."
        } else {
            $ExtId = $JsonParameters.PSobject.Properties["extId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isCompliant"))) { #optional property not found
            $IsCompliant = $null
        } else {
            $IsCompliant = $JsonParameters.PSobject.Properties["isCompliant"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastSyncedTime"))) { #optional property not found
            $LastSyncedTime = $null
        } else {
            $LastSyncedTime = $JsonParameters.PSobject.Properties["lastSyncedTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "configDrifts"))) { #optional property not found
            $ConfigDrifts = $null
        } else {
            $ConfigDrifts = $JsonParameters.PSobject.Properties["configDrifts"].value
        }

        $PSO = [PSCustomObject]@{
            "extId" = ${ExtId}
            "isCompliant" = ${IsCompliant}
            "lastSyncedTime" = ${LastSyncedTime}
            "configDrifts" = ${ConfigDrifts}
        }

        return $PSO
    }

}

