#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Node item containing attributes of node.

.PARAMETER NodeUuid
UUID of the host.
.PARAMETER BlockId
Rackable unit serial name.
.PARAMETER NodePosition
Position of a node in a rackable unit.
.PARAMETER HypervisorType
No description available.
.PARAMETER IsRoboMixedHypervisor
Indicates whether the hypervisor is robo mixed or not.
.PARAMETER HypervisorHostname
Name of the host.
.PARAMETER HypervisorVersion
Host version of the node.
.PARAMETER NosVersion
NOS software version of a node.
.PARAMETER IsLightCompute
Indicates whether the node is light compute or not.
.PARAMETER IpmiIp
No description available.
.PARAMETER DigitalCertificateMapList
List of objects containing digital_certificate_base64 and key_management_server_uuid fields for key management server.
.PARAMETER CvmIp
No description available.
.PARAMETER HypervisorIp
No description available.
.PARAMETER Model
Rackable unit model name.
.PARAMETER CurrentNetworkInterface
Current network interface of a node.
.PARAMETER Networks
Active and standby uplink information of the target nodes.
.PARAMETER LuksStatus
No description available.
.OUTPUTS

ClustermgmtV41ConfigNodeItem<PSCustomObject>
#>

function Initialize-NtnxV4ClustermgmtV41ConfigNodeItem {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${NodeUuid},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BlockId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NodePosition},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("AHV", "ESX", "HYPERV", "XEN", "NATIVEHOST", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${HypervisorType},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsRoboMixedHypervisor},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^(?!.*\.\.)(?!.*\.\-)(?!.*\-\.)(?!^\d+$)[a-zA-Z\d]([a-zA-Z\d.-]*[a-zA-Z\d])?$")]
        [String]
        ${HypervisorHostname},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HypervisorVersion},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NosVersion},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsLightCompute},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${IpmiIp},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${DigitalCertificateMapList},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CvmIp},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${HypervisorIp},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Model},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CurrentNetworkInterface},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Networks},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("NON_LUKS", "LUKS", "PARTIAL_LUKS", "UNKNOWN_LUKS", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${LuksStatus}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigNodeItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$HypervisorHostname -and $HypervisorHostname.length -gt 63) {
            throw "invalid value for 'HypervisorHostname', the character length must be smaller than or equal to 63."
        }

        if (!$DigitalCertificateMapList -and $DigitalCertificateMapList.length -gt 1024) {
            throw "invalid value for 'DigitalCertificateMapList', number of items must be less than or equal to 1024."
        }

        if (!$DigitalCertificateMapList -and $DigitalCertificateMapList.length -lt 0) {
            throw "invalid value for 'DigitalCertificateMapList', number of items must be greater than or equal to 0."
        }

        if (!$Networks -and $Networks.length -gt 1024) {
            throw "invalid value for 'Networks', number of items must be less than or equal to 1024."
        }

        if (!$Networks -and $Networks.length -lt 0) {
            throw "invalid value for 'Networks', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "nodeUuid" = ${NodeUuid}
            "blockId" = ${BlockId}
            "nodePosition" = ${NodePosition}
            "hypervisorType" = ${HypervisorType}
            "isRoboMixedHypervisor" = ${IsRoboMixedHypervisor}
            "hypervisorHostname" = ${HypervisorHostname}
            "hypervisorVersion" = ${HypervisorVersion}
            "nosVersion" = ${NosVersion}
            "isLightCompute" = ${IsLightCompute}
            "ipmiIp" = ${IpmiIp}
            "digitalCertificateMapList" = ${DigitalCertificateMapList}
            "cvmIp" = ${CvmIp}
            "hypervisorIp" = ${HypervisorIp}
            "model" = ${Model}
            "currentNetworkInterface" = ${CurrentNetworkInterface}
            "networks" = ${Networks}
            "luksStatus" = ${LuksStatus}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigNodeItem<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigNodeItem<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigNodeItem<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToClustermgmtV41ConfigNodeItem {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigNodeItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigNodeItem
        $AllProperties = ("nodeUuid", "blockId", "nodePosition", "hypervisorType", "isRoboMixedHypervisor", "hypervisorHostname", "hypervisorVersion", "nosVersion", "isLightCompute", "ipmiIp", "digitalCertificateMapList", "cvmIp", "hypervisorIp", "model", "currentNetworkInterface", "networks", "luksStatus")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nodeUuid"))) { #optional property not found
            $NodeUuid = $null
        } else {
            $NodeUuid = $JsonParameters.PSobject.Properties["nodeUuid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blockId"))) { #optional property not found
            $BlockId = $null
        } else {
            $BlockId = $JsonParameters.PSobject.Properties["blockId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nodePosition"))) { #optional property not found
            $NodePosition = $null
        } else {
            $NodePosition = $JsonParameters.PSobject.Properties["nodePosition"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hypervisorType"))) { #optional property not found
            $HypervisorType = $null
        } else {
            $HypervisorType = $JsonParameters.PSobject.Properties["hypervisorType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isRoboMixedHypervisor"))) { #optional property not found
            $IsRoboMixedHypervisor = $null
        } else {
            $IsRoboMixedHypervisor = $JsonParameters.PSobject.Properties["isRoboMixedHypervisor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hypervisorHostname"))) { #optional property not found
            $HypervisorHostname = $null
        } else {
            $HypervisorHostname = $JsonParameters.PSobject.Properties["hypervisorHostname"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hypervisorVersion"))) { #optional property not found
            $HypervisorVersion = $null
        } else {
            $HypervisorVersion = $JsonParameters.PSobject.Properties["hypervisorVersion"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nosVersion"))) { #optional property not found
            $NosVersion = $null
        } else {
            $NosVersion = $JsonParameters.PSobject.Properties["nosVersion"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isLightCompute"))) { #optional property not found
            $IsLightCompute = $null
        } else {
            $IsLightCompute = $JsonParameters.PSobject.Properties["isLightCompute"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ipmiIp"))) { #optional property not found
            $IpmiIp = $null
        } else {
            $IpmiIp = $JsonParameters.PSobject.Properties["ipmiIp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "digitalCertificateMapList"))) { #optional property not found
            $DigitalCertificateMapList = $null
        } else {
            $DigitalCertificateMapList = $JsonParameters.PSobject.Properties["digitalCertificateMapList"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cvmIp"))) { #optional property not found
            $CvmIp = $null
        } else {
            $CvmIp = $JsonParameters.PSobject.Properties["cvmIp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hypervisorIp"))) { #optional property not found
            $HypervisorIp = $null
        } else {
            $HypervisorIp = $JsonParameters.PSobject.Properties["hypervisorIp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "model"))) { #optional property not found
            $Model = $null
        } else {
            $Model = $JsonParameters.PSobject.Properties["model"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "currentNetworkInterface"))) { #optional property not found
            $CurrentNetworkInterface = $null
        } else {
            $CurrentNetworkInterface = $JsonParameters.PSobject.Properties["currentNetworkInterface"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "networks"))) { #optional property not found
            $Networks = $null
        } else {
            $Networks = $JsonParameters.PSobject.Properties["networks"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "luksStatus"))) { #optional property not found
            $LuksStatus = $null
        } else {
            $LuksStatus = $JsonParameters.PSobject.Properties["luksStatus"].value
        }

        $PSO = [PSCustomObject]@{
            "nodeUuid" = ${NodeUuid}
            "blockId" = ${BlockId}
            "nodePosition" = ${NodePosition}
            "hypervisorType" = ${HypervisorType}
            "isRoboMixedHypervisor" = ${IsRoboMixedHypervisor}
            "hypervisorHostname" = ${HypervisorHostname}
            "hypervisorVersion" = ${HypervisorVersion}
            "nosVersion" = ${NosVersion}
            "isLightCompute" = ${IsLightCompute}
            "ipmiIp" = ${IpmiIp}
            "digitalCertificateMapList" = ${DigitalCertificateMapList}
            "cvmIp" = ${CvmIp}
            "hypervisorIp" = ${HypervisorIp}
            "model" = ${Model}
            "currentNetworkInterface" = ${CurrentNetworkInterface}
            "networks" = ${Networks}
            "luksStatus" = ${LuksStatus}
        }

        return $PSO
    }

}

