#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Contains the required specifications for a password update operation.

.PARAMETER CurrentPassword
Existing password of a user account.
.PARAMETER NewPassword
New password for a user account.
.OUTPUTS

ClustermgmtV41ConfigChangePasswordSpec<PSCustomObject>
#>

function Initialize-NtnxV4ClustermgmtV41ConfigChangePasswordSpec {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CurrentPassword},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NewPassword}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigChangePasswordSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$CurrentPassword -and $CurrentPassword.length -gt 199) {
            throw "invalid value for 'CurrentPassword', the character length must be smaller than or equal to 199."
        }

        if (!$CurrentPassword -and $CurrentPassword.length -lt 8) {
            throw "invalid value for 'CurrentPassword', the character length must be greater than or equal to 8."
        }

        if ($null -eq $NewPassword) {
            throw "invalid value for 'NewPassword', 'NewPassword' cannot be null."
        }

        if ($NewPassword.length -gt 199) {
            throw "invalid value for 'NewPassword', the character length must be smaller than or equal to 199."
        }

        if ($NewPassword.length -lt 8) {
            throw "invalid value for 'NewPassword', the character length must be greater than or equal to 8."
        }


        $PSO = [PSCustomObject]@{
            "currentPassword" = ${CurrentPassword}
            "newPassword" = ${NewPassword}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigChangePasswordSpec<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigChangePasswordSpec<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigChangePasswordSpec<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToClustermgmtV41ConfigChangePasswordSpec {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigChangePasswordSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigChangePasswordSpec
        $AllProperties = ("currentPassword", "newPassword")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'newPassword' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "newPassword"))) {
            throw "Error! JSON cannot be serialized due to the required property 'newPassword' missing."
        } else {
            $NewPassword = $JsonParameters.PSobject.Properties["newPassword"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "currentPassword"))) { #optional property not found
            $CurrentPassword = $null
        } else {
            $CurrentPassword = $JsonParameters.PSobject.Properties["currentPassword"].value
        }

        $PSO = [PSCustomObject]@{
            "currentPassword" = ${CurrentPassword}
            "newPassword" = ${NewPassword}
        }

        return $PSO
    }

}

