#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ClustermgmtV41OperationsRebootType.

.DESCRIPTION

The type of the reboot operation to be performed. Possible values are: CONTROLLER_VM, HOST
#>

enum ClustermgmtV41OperationsRebootType {
    # enum value: "CONTROLLER_VM"
    CONTROLLER_VM
    # enum value: "HOST"
    HOST
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

