#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Recovery information for a cluster. Includes subnet information as users need to recreate subnets that may be destroyed by Cloud AZ failure.

.PARAMETER RecoveryStatus
No description available.
.PARAMETER Subnets
No description available.
.OUTPUTS

ClustermgmtV41ConfigRecoveryInfo<PSCustomObject>
#>

function Initialize-ClustermgmtV41ConfigRecoveryInfo {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${RecoveryStatus},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Subnets}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigRecoveryInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "recoveryStatus" = ${RecoveryStatus}
            "subnets" = ${Subnets}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigRecoveryInfo<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigRecoveryInfo<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigRecoveryInfo<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41ConfigRecoveryInfo {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigRecoveryInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigRecoveryInfo
        $AllProperties = ("recoveryStatus", "subnets")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "recoveryStatus"))) { #optional property not found
            $RecoveryStatus = $null
        } else {
            $RecoveryStatus = $JsonParameters.PSobject.Properties["recoveryStatus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "subnets"))) { #optional property not found
            $Subnets = $null
        } else {
            $Subnets = $JsonParameters.PSobject.Properties["subnets"].value
        }

        $PSO = [PSCustomObject]@{
            "recoveryStatus" = ${RecoveryStatus}
            "subnets" = ${Subnets}
        }

        return $PSO
    }

}

