#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

PCI Device entity description

.PARAMETER TenantId
A globally unique identifier that represents the tenant that owns this entity. The system automatically assigns it, and it and is immutable from an API consumer perspective (some use cases may cause this ID to change - For instance, a use case may require the transfer of ownership of the entity, but these cases are handled automatically on the server). 
.PARAMETER ExtId
A globally unique identifier of an instance that is suitable for external consumption. 
.PARAMETER Links
A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource. 
.PARAMETER ClusterExtId
UUID of the cluster.
.PARAMETER HostExtId
UUID of the host connected to the device
.PARAMETER State
No description available.
.PARAMETER Description
Human readable device description
.PARAMETER Configuration
No description available.
.PARAMETER OwnerVmExtId
UUID of the VM attached to that device when state is UVM_ASSIGNED or UVM_RESERVED
.PARAMETER Type
No description available.
.OUTPUTS

ClustermgmtV41AhvConfigPcieDevice<PSCustomObject>
#>

function Initialize-ClustermgmtV41AhvConfigPcieDevice {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${TenantId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ExtId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Links},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${ClusterExtId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${HostExtId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("UVM_AVAILABLE", "UVM_RESERVED", "UVM_ASSIGNED", "HOST_BROKEN", "HOST_UNUSED", "HOST_USED", "HOST_PARTITIONED", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${State},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Configuration},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")]
        [String]
        ${OwnerVmExtId},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("MASS_STORAGE_CONTROLLER", "NETWORK_CONTROLLER", "DISPLAY_CONTROLLER", "MULTIMEDIA_DEVICE", "MEMORY_CONTROLLER", "BRIDGE_DEVICE", "SIMPLE_COMMUNICATION_CONTROLLER", "BASE_SYSTEM_PERIPHERAL", "INPUT_DEVICE", "DOCKING_STATION", "PROCESSOR", "SERIAL_BUS_CONTROLLER", "WIRELESS_CONTROLLER", "INTELLIGENT_IO_CONTROLLER", "SATELLITE_COMMUNICATION_CONTROLLER", "ENCRYPTION_DECRYPTION_CONTROLLER", "DATA_ACQUISITION_AND_SIGNAL_PROCESSING_CONTROLLER", "PROCESSING_ACCELERATOR", "NON_ESSENTIAL_INSTRUMENTATION", "UNKNOWN", "REDACTED")]
        [PSCustomObject]
        ${Type}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41AhvConfigPcieDevice' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Links -and $Links.length -gt 20) {
            throw "invalid value for 'Links', number of items must be less than or equal to 20."
        }

        if (!$Links -and $Links.length -lt 0) {
            throw "invalid value for 'Links', number of items must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "clusterExtId" = ${ClusterExtId}
            "hostExtId" = ${HostExtId}
            "state" = ${State}
            "description" = ${Description}
            "configuration" = ${Configuration}
            "ownerVmExtId" = ${OwnerVmExtId}
            "type" = ${Type}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41AhvConfigPcieDevice<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41AhvConfigPcieDevice<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41AhvConfigPcieDevice<PSCustomObject>
#>
function ConvertFrom-JsonToClustermgmtV41AhvConfigPcieDevice {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41AhvConfigPcieDevice' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41AhvConfigPcieDevice
        $AllProperties = ("tenantId", "extId", "links", "clusterExtId", "hostExtId", "state", "description", "configuration", "ownerVmExtId", "type")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extId"))) { #optional property not found
            $ExtId = $null
        } else {
            $ExtId = $JsonParameters.PSobject.Properties["extId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "links"))) { #optional property not found
            $Links = $null
        } else {
            $Links = $JsonParameters.PSobject.Properties["links"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "clusterExtId"))) { #optional property not found
            $ClusterExtId = $null
        } else {
            $ClusterExtId = $JsonParameters.PSobject.Properties["clusterExtId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hostExtId"))) { #optional property not found
            $HostExtId = $null
        } else {
            $HostExtId = $JsonParameters.PSobject.Properties["hostExtId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "state"))) { #optional property not found
            $State = $null
        } else {
            $State = $JsonParameters.PSobject.Properties["state"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "configuration"))) { #optional property not found
            $Configuration = $null
        } else {
            $Configuration = $JsonParameters.PSobject.Properties["configuration"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ownerVmExtId"))) { #optional property not found
            $OwnerVmExtId = $null
        } else {
            $OwnerVmExtId = $JsonParameters.PSobject.Properties["ownerVmExtId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        $PSO = [PSCustomObject]@{
            "tenantId" = ${TenantId}
            "extId" = ${ExtId}
            "links" = ${Links}
            "clusterExtId" = ${ClusterExtId}
            "hostExtId" = ${HostExtId}
            "state" = ${State}
            "description" = ${Description}
            "configuration" = ${Configuration}
            "ownerVmExtId" = ${OwnerVmExtId}
            "type" = ${Type}
        }

        return $PSO
    }

}

