#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ClustermgmtV41ConfigAddressType.

.DESCRIPTION

Indicates whether the address type is IPV4/IPV6.
#>

enum ClustermgmtV41ConfigAddressType {
    # enum value: "IPV4"
    IPV4
    # enum value: "IPV6"
    IPV6
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

