#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Block item containing block serial and rack name.

.PARAMETER BlockId
Rackable unit serial name.
.PARAMETER RackName
Rack name.
.OUTPUTS

ClustermgmtV41ConfigBlockItem<PSCustomObject>
#>

function Initialize-NtnxV4ClustermgmtV41ConfigBlockItem {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BlockId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RackName}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigBlockItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$RackName -and $RackName.length -gt 64) {
            throw "invalid value for 'RackName', the character length must be smaller than or equal to 64."
        }


        $PSO = [PSCustomObject]@{
            "blockId" = ${BlockId}
            "rackName" = ${RackName}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClustermgmtV41ConfigBlockItem<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClustermgmtV41ConfigBlockItem<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClustermgmtV41ConfigBlockItem<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToClustermgmtV41ConfigBlockItem {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4ClustermgmtV41ConfigBlockItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4ClustermgmtV41ConfigBlockItem
        $AllProperties = ("blockId", "rackName")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blockId"))) { #optional property not found
            $BlockId = $null
        } else {
            $BlockId = $JsonParameters.PSobject.Properties["blockId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rackName"))) { #optional property not found
            $RackName = $null
        } else {
            $RackName = $JsonParameters.PSobject.Properties["rackName"].value
        }

        $PSO = [PSCustomObject]@{
            "blockId" = ${BlockId}
            "rackName" = ${RackName}
        }

        return $PSO
    }

}

