#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ClustermgmtV41ConfigSoftwareTypeRef.

.DESCRIPTION

Software type.
#>

enum ClustermgmtV41ConfigSoftwareTypeRef {
    # enum value: "NOS"
    NOS
    # enum value: "NCC"
    NCC
    # enum value: "PRISM_CENTRAL"
    PRISM_CENTRAL
    # enum value: "UNKNOWN"
    UNKNOWN
    # enum value: "REDACTED"
    REDACTED
}

