#
# Nutanix Cluster Management APIs
# Manage Hosts, Clusters and other Infrastructure.
# Version: 4.1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

REST response for all response codes in API path /clustermgmt/v4.1/config/clusters/{clusterExtId}/snmp/traps/{extId} Put operation

.PARAMETER Metadata
No description available.
.PARAMETER VarData
No description available.
.OUTPUTS

UpdateSnmpTrapById202Response<PSCustomObject>
#>

function Initialize-NtnxV4UpdateSnmpTrapById202Response {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Metadata},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VarData}
    )

    Process {
        'Creating PSCustomObject: NtnxV4.clustermgmt => NtnxV4UpdateSnmpTrapById202Response' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "metadata" = ${Metadata}
            "data" = ${VarData}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UpdateSnmpTrapById202Response<PSCustomObject>

.DESCRIPTION

Convert from JSON to UpdateSnmpTrapById202Response<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UpdateSnmpTrapById202Response<PSCustomObject>
#>
function ConvertFrom-NtnxV4JsonToUpdateSnmpTrapById202Response {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: NtnxV4.clustermgmt => NtnxV4UpdateSnmpTrapById202Response' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NtnxV4UpdateSnmpTrapById202Response
        $AllProperties = ("metadata", "data")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "metadata"))) { #optional property not found
            $Metadata = $null
        } else {
            $Metadata = $JsonParameters.PSobject.Properties["metadata"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data"))) { #optional property not found
            $VarData = $null
        } else {
            $VarData = $JsonParameters.PSobject.Properties["data"].value
        }

        $PSO = [PSCustomObject]@{
            "metadata" = ${Metadata}
            "data" = ${VarData}
        }

        return $PSO
    }

}

